SELECT 'EVENTOS DESTANQUEADOS - CASA' AS TYPE_OF_TXN,  COUNT(DISTINCT trn_ref_no) AS RECORDS_COUNT FROM ACTB_DAILY_LOG
WHERE  trn_dt =  to_date('%NEXT_DATE%','dd-mm-yyyy')
AND txn_init_date = to_date('%PROCESSING_DATE%','dd-mm-yyyy') AND MODULE <> 'CL'
--SPLIT--
SELECT 'EVENTOS DESTANQUEADOS - CL' AS TYPE_OF_TXN,  COUNT(DISTINCT related_account) AS RECORDS_COUNT
  FROM ACTB_DAILY_LOG
 WHERE trn_dt = to_date('%NEXT_DATE%','dd-mm-yyyy')
   AND txn_init_date = to_date('%PROCESSING_DATE%','dd-mm-yyyy')
   AND MODULE = 'CL'
--SPLIT--
SELECT 'PENALIDAD CREDITOS' AS TYPE_OF_TXN, COUNT(1) AS RECORDS_COUNT
  FROM CLTB_ACC_PENL_PROCESED
 WHERE processing_date = to_date('%PROCESSING_DATE%','dd-mm-yyyy')
   AND status = 'P'
--SPLIT--
SELECT 'SECUENCIAS RESETEADAS EN BOD' AS TYPE_OF_TXN, COUNT(1) AS RECORDS_COUNT FROM CSTB_PROCESS
