from __future__ import annotations

import hashlib
import re
import sys
import tempfile
import threading
import unittest
from collections import deque
from dataclasses import replace
from pathlib import Path
from typing import Sequence


SRC_DIR = Path(__file__).resolve().parents[1] / "src"
sys.path.insert(0, str(SRC_DIR))

from features.output_file_generation import (  # noqa: E402
    DataSourceChoice,
    GenerationRequest,
    OracleTarget,
    OutputFileGenerationService,
)
from features.output_file_generation.service import (  # noqa: E402
    GenerationCancelled,
    OutputFileGenerationError,
    _parse_candidates,
)
from spools_cl_accounts.sqlcl import RunResult  # noqa: E402


class _FakeConfig:
    def __init__(self, sqlcl_path: Path) -> None:
        self.sqlcl_path = sqlcl_path
        self.credential_calls: list[tuple[str, str, str]] = []
        self.database_failover = {
            "chile_prod_oci": True,
            "colombia_prod_oci": True,
        }
        self.credential = {
            "user": "fake_user",
            "schema": "",
            "password_enc": "encrypted-for-test",
            "tns": "FXBFCL_19C_PROD_OCI",
            "bucket": "shared_prod",
        }
        self.credentials = {
            "chile": {
                "PROD-DB": {
                    "SHARED-PROD": self.credential,
                }
            }
        }

    def get(self, key: str, default=None):
        if key == "sqlcl_path":
            return str(self.sqlcl_path)
        if key == "database_failover":
            return self.database_failover
        return default

    def get_credential(
        self,
        country: str,
        database_key: str,
        credential_key: str,
    ) -> dict[str, str] | None:
        self.credential_calls.append((country, database_key, credential_key))
        return (
            self.credentials.get(country.lower(), {})
            .get(database_key.upper(), {})
            .get(credential_key.upper())
        )

    def all_credentials(self) -> dict:
        return self.credentials


_QueuedResponse = Sequence[str] | RunResult


def _hex(value: str) -> str:
    return value.encode("utf-8").hex().upper()


def _oficowcg_row(
    status: str,
    fields: Sequence[str],
    *,
    error_code: str = "",
    error_params: str = "",
) -> str:
    if len(fields) != 11:
        raise AssertionError("OFICOWCG fixtures need eleven data fields")
    return "|".join(
        _hex(value)
        for value in (status, error_code, error_params, *fields)
    )


def _oficowcg_colombia_row(
    status: str,
    fields: Sequence[str],
    txn_status: str,
    *,
    error_code: str = "",
    error_params: str = "",
) -> str:
    if len(fields) != 11:
        raise AssertionError("Colombia OFICOWCG fixtures need eleven data fields")
    return "|".join(
        _hex(value)
        for value in (status, error_code, error_params, *fields, txn_status)
    )


def _oficowcg_coverage(
    upload_rows: int,
    *,
    nonnull_refs: int | None = None,
    distinct_refs: int | None = None,
    one_gic: int | None = None,
    one_output: int | None = None,
    no_output: int = 0,
    multiple_outputs: int = 0,
    orphan_branch_b: int = 0,
) -> str:
    values = (
        upload_rows,
        upload_rows if nonnull_refs is None else nonnull_refs,
        upload_rows if distinct_refs is None else distinct_refs,
        upload_rows if one_gic is None else one_gic,
        upload_rows if one_output is None else one_output,
        no_output,
        multiple_outputs,
        orphan_branch_b,
    )
    return "|".join(str(value) for value in values)


def _ofcrelvp_row(
    status: str,
    branch: str,
    account: str,
    esn: str,
    error_code: str = "",
    error_param: str = "",
) -> str:
    return "|".join(
        _hex(value)
        for value in (status, branch, account, esn, error_code, error_param)
    )


def _oacmclos_row(
    status: str,
    branch: str,
    account: str,
    error_code: str = "",
    error_param: str = "",
) -> str:
    return "|".join(
        _hex(value)
        for value in (status, branch, account, error_code, error_param)
    )


def _cladchgo_row(
    status: str,
    account: str,
    internal_ref: str,
    error_code: str = "",
    error_param: str = "",
) -> str:
    return "|".join(
        _hex(value)
        for value in (status, account, internal_ref, error_code, error_param)
    )


class _QueuedSqlclRunner:
    """Return queued rows inside the unique markers generated by each query."""

    def __init__(self, responses: Sequence[_QueuedResponse]) -> None:
        self.responses = deque(responses)
        self.scripts: list[str] = []
        self.connections: list[str] = []
        self.timeouts: list[float | None] = []

    @property
    def pending(self) -> int:
        return len(self.responses)

    def run_script(
        self,
        connection: str,
        script_path: str | Path,
        args: list[str] | None = None,
        timeout: float | None = None,
        cancel_event: threading.Event | None = None,
    ) -> RunResult:
        del args, cancel_event
        if not self.responses:
            raise AssertionError("SQLcl was called more times than expected")

        script = Path(script_path).read_text(encoding="utf-8")
        self.scripts.append(script)
        self.connections.append(connection)
        self.timeouts.append(timeout)
        response = self.responses.popleft()
        if isinstance(response, RunResult):
            return response

        begin = re.search(r"^prompt (.+_BEGIN__)$", script, re.MULTILINE)
        end = re.search(r"^prompt (.+_END__)$", script, re.MULTILINE)
        if begin is None or end is None:
            raise AssertionError("The generated SQL script is not framed")
        rows = "\n".join(response)
        stdout = f"{begin.group(1)}\n{rows}\n{end.group(1)}\n"
        return RunResult(0, stdout, "")


class _CancellingOnLastRunner(_QueuedSqlclRunner):
    def run_script(
        self,
        connection: str,
        script_path: str | Path,
        args: list[str] | None = None,
        timeout: float | None = None,
        cancel_event: threading.Event | None = None,
    ) -> RunResult:
        result = super().run_script(
            connection,
            script_path,
            args=args,
            timeout=timeout,
            cancel_event=cancel_event,
        )
        if not self.responses and cancel_event is not None:
            cancel_event.set()
        return result


class OutputFileGenerationTests(unittest.TestCase):
    def setUp(self) -> None:
        temporary = tempfile.TemporaryDirectory()
        self.addCleanup(temporary.cleanup)
        self.root = Path(temporary.name)
        self.sqlcl_path = self.root / "sql.exe"
        self.sqlcl_path.touch()
        self.config = _FakeConfig(self.sqlcl_path)
        self.target = OracleTarget(
            country="chile",
            database_key="prod-db",
            credential_key="shared-prod",
            tns="FXBFCL_19C_PROD_OCI",
            label="Chile PROD",
        )

    def _service(
        self,
        *responses: _QueuedResponse,
    ) -> tuple[OutputFileGenerationService, _QueuedSqlclRunner]:
        runner = _QueuedSqlclRunner(responses)
        service = OutputFileGenerationService(
            self.config,
            runner_factory=lambda _path: runner,
            decryptor=lambda _encrypted: "fake-password",
            output_root=self.root / "output",
        )
        return service, runner

    def _request(
        self,
        *,
        process_ref_no: str = "1234567",
        overwrite: bool = False,
        interface_code: str | None = None,
    ) -> GenerationRequest:
        return GenerationRequest(
            target=self.target,
            process_ref_no=process_ref_no,
            overwrite=overwrite,
            interface_code=interface_code,
        )

    def test_non_ui_request_keeps_fail_safe_overwrite_default(self) -> None:
        request = GenerationRequest(
            target=self.target,
            process_ref_no="1234567",
        )

        self.assertFalse(request.overwrite)

    def test_ofdobiel_auto_archive_writes_exact_lf_utf8_payload_and_sha(self) -> None:
        body_lines = [
            "BDY;C;000000001;E;P;;;",
            "BDY;C;000000002;D;E;X01;Descripción inválida;",
        ]
        service, runner = self._service(
            ["UPLOAD_MASTER|ARCHIVE|IFDOBIEL|2"],
            ["IFDOBIEL|OFDOBIEL"],
            ["20260731|1|1"],
            [
                "P|||BDY;C;000000001;E;P;",
                "E|583031||BDY;C;000000002;D;E;",
            ],
            [
                "583031|1|"
                + "Descripci\u00f3n inv\u00e1lida".encode("utf-8").hex().upper()
            ],
            [
                "583031|1|"
                + "Descripci\u00f3n inv\u00e1lida".encode("utf-8").hex().upper()
            ],
            ["2|1|1"],
        )

        request = self._request()
        self.assertEqual(
            set(request.__dataclass_fields__),
            {
                "target",
                "process_ref_no",
                "overwrite",
                "interface_code",
                "input_file_date",
            },
        )
        result = service.generate(request)

        expected_lines = (
            "HDR;OFDOBIEL.txt;20260731;",
            *body_lines,
            "TLR;2;",
        )
        expected_payload = ("\n".join(expected_lines) + "\n").encode("utf-8")
        self.assertEqual(result.process_ref_no, "1234567")
        self.assertEqual(result.input_code, "IFDOBIEL")
        self.assertEqual(result.output_code, "OFDOBIEL")
        self.assertEqual(result.file_date, "20260731")
        self.assertIs(result.source, DataSourceChoice.ARCHIVE)
        self.assertEqual(result.body_count, 2)
        self.assertEqual(result.lines, expected_lines)
        self.assertEqual(result.output_path.name, "OFDOBIEL_20260731.TXT")
        self.assertEqual(result.output_path.read_bytes(), expected_payload)
        self.assertNotIn(b"\r", expected_payload)
        self.assertIn("Descripción inválida".encode("utf-8"), expected_payload)
        self.assertEqual(result.sha256, hashlib.sha256(expected_payload).hexdigest())
        self.assertTrue(
            any(
                "from GITA_UPLOAD_MASTER" in script
                and "trim(fld1) = 'BDY'" in script
                for script in runner.scripts
            )
        )
        self.assertEqual(runner.pending, 0)

    def test_chile_connection_error_restarts_the_whole_generation_on_dr(self) -> None:
        self.config.credentials["chile"]["PROD-DB-DR"] = {
            "SHARED-PROD": {
                **self.config.credential,
                "tns": "FXBFCL_19C_PROD_OCI_DR",
            }
        }
        service, runner = self._service(
            RunResult(
                1,
                "\n  USER          = fake_user\n"
                "  URL           = jdbc:oracle:thin:@FXBFCL_19C_PROD_OCI\n"
                "  Error Message = Listener refused the connection with the "
                "following error:\n"
                "ORA-12514, TNS:listener does not currently know of service "
                "requested in connect descriptor\n",
                "",
            ),
            ["UPLOAD_MASTER|ARCHIVE|IFDOBIEL|1"],
            ["IFDOBIEL|OFDOBIEL"],
            ["20260731|1|1"],
            ["P|||BDY;C;000000001;E;P;"],
            ["1|1|1"],
        )

        with self.assertLogs(
            "features.output_file_generation.service",
            level="INFO",
        ) as captured:
            result = service.generate(self._request(interface_code="OFDOBIEL"))

        primary = "fake_user/fake-password@FXBFCL_19C_PROD_OCI"
        fallback = "fake_user/fake-password@FXBFCL_19C_PROD_OCI_DR"
        self.assertEqual(runner.connections, [primary, *([fallback] * 5)])
        self.assertEqual(result.output_code, "OFDOBIEL")
        self.assertEqual(runner.pending, 0)
        logs = "\n".join(captured.output)
        self.assertIn("FXBFCL_19C_PROD_OCI_DR", logs)
        self.assertIn("Output reconstruction completed", logs)
        self.assertIn("tns=FXBFCL_19C_PROD_OCI_DR", logs)

    def test_mid_generation_connection_loss_restarts_discovery_on_dr(self) -> None:
        self.config.credentials["chile"]["PROD-DB-DR"] = {
            "SHARED-PROD": {
                **self.config.credential,
                "tns": "FXBFCL_19C_PROD_OCI_DR",
            }
        }
        service, runner = self._service(
            ["UPLOAD_MASTER|ARCHIVE|IFDOBIEL|1"],
            RunResult(1, "", "ORA-03113: end-of-file on communication channel"),
            ["UPLOAD_MASTER|ARCHIVE|IFDOBIEL|1"],
            ["IFDOBIEL|OFDOBIEL"],
            ["20260731|1|1"],
            ["P|||BDY;C;000000001;E;P;"],
            ["1|1|1"],
        )

        result = service.generate(self._request(interface_code="OFDOBIEL"))

        primary = "fake_user/fake-password@FXBFCL_19C_PROD_OCI"
        fallback = "fake_user/fake-password@FXBFCL_19C_PROD_OCI_DR"
        self.assertEqual(
            runner.connections,
            [primary, primary, *([fallback] * 5)],
        )
        self.assertEqual(
            sum("GITU_UPLOAD_MASTER" in script for script in runner.scripts),
            2,
        )
        self.assertEqual(result.output_code, "OFDOBIEL")
        self.assertEqual(runner.pending, 0)

    def test_chile_dr_connection_error_can_fall_back_to_primary_oci(self) -> None:
        primary_credential = dict(self.config.credential)
        dr_credential = {
            **self.config.credential,
            "tns": "FXBFCL_19C_PROD_OCI_DR",
        }
        self.config.credentials["chile"] = {
            "PROD-DB": {"SHARED-PROD": primary_credential},
            "PROD-DB-DR": {"SHARED-PROD": dr_credential},
        }
        dr_target = OracleTarget(
            country="chile",
            database_key="prod-db-dr",
            credential_key="shared-prod",
            tns="FXBFCL_19C_PROD_OCI_DR",
            label="Chile PROD DR",
        )
        service, runner = self._service(
            RunResult(1, "", "ORA-12541: TNS:no listener"),
            ["UPLOAD_MASTER|ARCHIVE|IFDOBIEL|1"],
            ["IFDOBIEL|OFDOBIEL"],
            ["20260731|1|1"],
            ["P|||BDY;C;000000001;E;P;"],
            ["1|1|1"],
        )

        with self.assertLogs(
            "features.output_file_generation.service",
            level="INFO",
        ) as captured:
            result = service.generate(
                GenerationRequest(
                    target=dr_target,
                    process_ref_no="1234567",
                    interface_code="OFDOBIEL",
                )
            )

        dr = "fake_user/fake-password@FXBFCL_19C_PROD_OCI_DR"
        primary = "fake_user/fake-password@FXBFCL_19C_PROD_OCI"
        self.assertEqual(runner.connections, [dr, *([primary] * 5)])
        self.assertEqual(result.output_code, "OFDOBIEL")
        logs = "\n".join(captured.output)
        self.assertIn("tns=FXBFCL_19C_PROD_OCI", logs)
        self.assertEqual(runner.pending, 0)

    def test_working_primary_does_not_decrypt_unused_fallback_credential(self) -> None:
        self.config.credentials["chile"]["PROD-DB-DR"] = {
            "SHARED-PROD": {
                **self.config.credential,
                "password_enc": "fallback-encrypted",
                "tns": "FXBFCL_19C_PROD_OCI_DR",
            }
        }
        runner = _QueuedSqlclRunner(
            (
                ["UPLOAD_MASTER|ARCHIVE|IFDOBIEL|1"],
                ["IFDOBIEL|OFDOBIEL"],
                ["20260731|1|1"],
                ["P|||BDY;C;000000001;E;P;"],
                ["1|1|1"],
            )
        )
        decrypted: list[str] = []

        def decryptor(encrypted: str) -> str:
            decrypted.append(encrypted)
            if encrypted == "fallback-encrypted":
                raise AssertionError("Fallback password was decrypted eagerly")
            return "fake-password"

        service = OutputFileGenerationService(
            self.config,
            runner_factory=lambda _path: runner,
            decryptor=decryptor,
            output_root=self.root / "output",
        )

        result = service.generate(self._request(interface_code="OFDOBIEL"))

        self.assertEqual(result.output_code, "OFDOBIEL")
        self.assertEqual(decrypted, ["encrypted-for-test"])
        self.assertEqual(
            runner.connections,
            ["fake_user/fake-password@FXBFCL_19C_PROD_OCI"] * 5,
        )

    def test_output_generation_does_not_fail_over_for_functional_sql_error(self) -> None:
        self.config.credentials["chile"]["PROD-DB-DR"] = {
            "SHARED-PROD": {
                **self.config.credential,
                "tns": "FXBFCL_19C_PROD_OCI_DR",
            }
        }
        service, runner = self._service(
            RunResult(1, "", "ORA-00942: table or view does not exist"),
            ["UPLOAD_MASTER|ARCHIVE|IFDOBIEL|1"],
        )

        with self.assertRaisesRegex(OutputFileGenerationError, "ORA-00942"):
            service.generate(self._request(interface_code="OFDOBIEL"))

        self.assertEqual(
            runner.connections,
            ["fake_user/fake-password@FXBFCL_19C_PROD_OCI"],
        )
        self.assertEqual(runner.pending, 1)

    def test_output_generation_does_not_fail_over_for_authentication_error(self) -> None:
        self.config.credentials["chile"]["PROD-DB-DR"] = {
            "SHARED-PROD": {
                **self.config.credential,
                "tns": "FXBFCL_19C_PROD_OCI_DR",
            }
        }
        service, runner = self._service(
            RunResult(
                1,
                "",
                "ORA-01017: invalid username/password; logon denied for "
                "fake_user/fake-password@FXBFCL_19C_PROD_OCI",
            ),
            ["UPLOAD_MASTER|ARCHIVE|IFDOBIEL|1"],
        )

        with self.assertRaises(OutputFileGenerationError) as raised:
            service.generate(self._request(interface_code="OFDOBIEL"))

        self.assertIn("ORA-01017", str(raised.exception))
        self.assertIn("[connection redacted]", str(raised.exception))
        self.assertNotIn("fake-password", str(raised.exception))
        self.assertEqual(
            runner.connections,
            ["fake_user/fake-password@FXBFCL_19C_PROD_OCI"],
        )
        self.assertEqual(runner.pending, 1)

    def test_output_generation_does_not_fail_over_after_timeout(self) -> None:
        self.config.credentials["chile"]["PROD-DB-DR"] = {
            "SHARED-PROD": {
                **self.config.credential,
                "tns": "FXBFCL_19C_PROD_OCI_DR",
            }
        }
        service, runner = self._service(
            RunResult(124, "ORA-12514", "Timed out after 120s"),
            ["UPLOAD_MASTER|ARCHIVE|IFDOBIEL|1"],
        )

        with self.assertRaisesRegex(OutputFileGenerationError, "Timed out after 120s"):
            service.generate(self._request(interface_code="OFDOBIEL"))

        self.assertEqual(
            runner.connections,
            ["fake_user/fake-password@FXBFCL_19C_PROD_OCI"],
        )
        self.assertEqual(runner.pending, 1)

    def test_output_generation_does_not_fail_over_after_cancel(self) -> None:
        self.config.credentials["chile"]["PROD-DB-DR"] = {
            "SHARED-PROD": {
                **self.config.credential,
                "tns": "FXBFCL_19C_PROD_OCI_DR",
            }
        }
        service, runner = self._service(
            RunResult(130, "ORA-12514", "Cancelled by user"),
            ["UPLOAD_MASTER|ARCHIVE|IFDOBIEL|1"],
        )

        with self.assertRaisesRegex(GenerationCancelled, "cancelled"):
            service.generate(self._request(interface_code="OFDOBIEL"))

        self.assertEqual(
            runner.connections,
            ["fake_user/fake-password@FXBFCL_19C_PROD_OCI"],
        )
        self.assertEqual(runner.pending, 1)

    def test_disabled_output_failover_never_uses_the_equivalent_database(self) -> None:
        self.config.database_failover["chile_prod_oci"] = False
        self.config.credentials["chile"]["PROD-DB-DR"] = {
            "SHARED-PROD": {
                **self.config.credential,
                "tns": "FXBFCL_19C_PROD_OCI_DR",
            }
        }
        service, runner = self._service(
            RunResult(1, "", "ORA-12514: listener does not know this service"),
            ["UPLOAD_MASTER|ARCHIVE|IFDOBIEL|1"],
        )

        with self.assertRaisesRegex(OutputFileGenerationError, "ORA-12514"):
            service.generate(self._request(interface_code="OFDOBIEL"))

        self.assertEqual(
            runner.connections,
            ["fake_user/fake-password@FXBFCL_19C_PROD_OCI"],
        )
        self.assertEqual(runner.pending, 1)

    def test_missing_alternative_credential_does_not_retry_elsewhere(self) -> None:
        service, runner = self._service(
            RunResult(1, "", "ORA-12514: listener does not know this service"),
            ["UPLOAD_MASTER|ARCHIVE|IFDOBIEL|1"],
        )

        with self.assertRaisesRegex(OutputFileGenerationError, "ORA-12514"):
            service.generate(self._request(interface_code="OFDOBIEL"))

        self.assertEqual(
            runner.connections,
            ["fake_user/fake-password@FXBFCL_19C_PROD_OCI"],
        )
        self.assertEqual(runner.pending, 1)

    def test_ambiguous_alternative_credentials_disable_output_failover(self) -> None:
        fallback = {
            **self.config.credential,
            "tns": "FXBFCL_19C_PROD_OCI_DR",
        }
        self.config.credentials["chile"].update(
            {
                "DR-STORE-A": {
                    "DR-LOGIN-A": {**fallback, "user": "dr_user_a"},
                },
                "DR-STORE-B": {
                    "DR-LOGIN-B": {**fallback, "user": "dr_user_b"},
                },
            }
        )
        service, runner = self._service(
            RunResult(1, "", "ORA-12514: listener does not know this service"),
            ["UPLOAD_MASTER|ARCHIVE|IFDOBIEL|1"],
        )

        with self.assertLogs(
            "features.output_file_generation.service",
            level="WARNING",
        ) as captured:
            with self.assertRaisesRegex(OutputFileGenerationError, "ORA-12514"):
                service.generate(self._request(interface_code="OFDOBIEL"))

        self.assertEqual(
            runner.connections,
            ["fake_user/fake-password@FXBFCL_19C_PROD_OCI"],
        )
        self.assertEqual(runner.pending, 1)
        self.assertIn("ambiguous-or-missing-PROD-credential", "\n".join(captured.output))

    def test_output_failover_stops_after_both_equivalent_databases_fail(self) -> None:
        self.config.credentials["chile"]["PROD-DB-DR"] = {
            "SHARED-PROD": {
                **self.config.credential,
                "tns": "FXBFCL_19C_PROD_OCI_DR",
            }
        }
        service, runner = self._service(
            RunResult(1, "", "ORA-12514: primary listener unavailable"),
            RunResult(1, "", "ORA-12541: fallback listener unavailable"),
            ["UPLOAD_MASTER|ARCHIVE|IFDOBIEL|1"],
        )

        with self.assertLogs(
            "features.output_file_generation.service",
            level="WARNING",
        ) as captured:
            with self.assertRaisesRegex(OutputFileGenerationError, "ORA-12541") as raised:
                service.generate(self._request(interface_code="OFDOBIEL"))

        self.assertEqual(
            runner.connections,
            [
                "fake_user/fake-password@FXBFCL_19C_PROD_OCI",
                "fake_user/fake-password@FXBFCL_19C_PROD_OCI_DR",
            ],
        )
        self.assertEqual(runner.pending, 1)
        diagnostics = str(raised.exception) + "\n" + "\n".join(captured.output)
        self.assertNotIn("fake-password", diagnostics)

    def test_archive_rejects_error_message_catalog_change_before_save(self) -> None:
        service, runner = self._service(
            ["UPLOAD_MASTER|ARCHIVE|IFDOBIEL|1"],
            ["IFDOBIEL|OFDOBIEL"],
            ["20260731|1|1"],
            ["E|583031||BDY;C;000000002;D;E;"],
            ["583031|1|" + "Before $1".encode("utf-8").hex().upper()],
            ["583031|1|" + "After $1".encode("utf-8").hex().upper()],
        )

        with self.assertRaisesRegex(
            OutputFileGenerationError,
            "error-message definitions changed",
        ):
            service.generate(self._request())

        self.assertEqual(runner.pending, 0)
        self.assertFalse((self.root / "output").exists())

    def test_accblock_active_resolves_date_and_uses_database_timestamp(self) -> None:
        body_lines = [
            "BDY;000000001;100;CLP;BLOQUEO;Y;;;",
            "BDY;000000002;200;CLP;BLOQUEO;N;E001;Bloqueo;",
        ]
        service, runner = self._service(
            ["UPLOAD_MASTER|ACTIVE|ACCBLOCK|2"],
            ["ACCBLOCK|ACCBLKOU"],
            ["20260730|1|1"],
            ["142355"],
            [f"{status}|{line}" for status, line in zip(("P", "E"), body_lines)],
            [f"{status}|{line}" for status, line in zip(("P", "E"), body_lines)],
            ["20260730|1|1"],
            ["2|1|1"],
        )

        result = service.generate(self._request())

        self.assertEqual(result.file_date, "20260730")
        self.assertIs(result.source, DataSourceChoice.ACTIVE)
        self.assertEqual(
            result.lines,
            (
                "HDR;ACCBLKOU_20260730.TXT;20260730142355;",
                *body_lines,
                "FTR;1;1;",
            ),
        )
        self.assertEqual(result.output_path.name, "ACCBLKOU_20260730.TXT")
        self.assertTrue(any("from GITB_FILE_LOG" in script for script in runner.scripts))
        self.assertTrue(
            any(
                "from GITU_UPLOAD_MASTER" in script
                and "decode(rtrim(status)" in script
                for script in runner.scripts
            )
        )
        time_index = next(
            index
            for index, script in enumerate(runner.scripts)
            if "to_char(sysdate" in script.lower()
        )
        body_index = next(
            index
            for index, script in enumerate(runner.scripts)
            if "decode(rtrim(status)" in script
        )
        self.assertLess(time_index, body_index)
        self.assertEqual(runner.pending, 0)

    def test_oflocrec_archive_reconstructs_exact_qa_contract(self) -> None:
        body_lines = [
            "BDY;000000001;100;CLP;Y;;;",
            "BDY;000000002;200;USD;N;E001;CUENTA~;",
        ]
        service, runner = self._service(
            ["UPLOAD_MASTER|ARCHIVE|IFLOCREC|3"],
            ["IFLOCREC|OFLOCREC"],
            ["20240517|1|1"],
            ["094512"],
            [f"{status}|{line}" for status, line in zip(("P", "E"), body_lines)],
            ["E|1", "P|2"],
            ["3|1|1"],
        )

        result = service.generate(self._request(process_ref_no="2309481"))

        self.assertEqual((result.input_code, result.output_code), ("IFLOCREC", "OFLOCREC"))
        self.assertEqual(result.file_date, "20240517")
        self.assertIs(result.source, DataSourceChoice.ARCHIVE)
        self.assertEqual(
            result.lines,
            (
                "HDR;OFLOCREC_20240517094512;17052024094512;",
                *body_lines,
                "FTR;2;1;",
            ),
        )
        self.assertEqual(result.output_path.name, "OFLOCREC_20240517.TXT")
        self.assertEqual(result.status_counts, {"E": 1, "P": 1})
        self.assertEqual(
            result.output_path.read_text(encoding="utf-8"),
            "\n".join(result.lines) + "\n",
        )
        time_scripts = [
            script for script in runner.scripts if "to_char(sysdate" in script.lower()
        ]
        self.assertEqual(len(time_scripts), 1)
        self.assertIn("to_char(sysdate, 'HHMISS')", time_scripts[0])
        self.assertTrue(
            any(
                "from GITA_UPLOAD_MASTER" in script
                and "interface_code)) = 'IFLOCREC'" in script
                and "order by record_reference" in script.lower()
                for script in runner.scripts
            )
        )
        body_index = next(
            index
            for index, script in enumerate(runner.scripts)
            if "interface_code)) = 'IFLOCREC'" in script
            and "trim(fld1) = 'BDY'" in script
        )
        time_index = next(
            index
            for index, script in enumerate(runner.scripts)
            if "to_char(sysdate" in script.lower()
        )
        self.assertLess(time_index, body_index)
        self.assertEqual(runner.pending, 0)

    def test_oflocrec_active_footer_population_is_revalidated(self) -> None:
        body_rows = [
            "P|BDY;000000001;100;CLP;Y;;;",
            "E|BDY;000000002;200;USD;N;E001;CUENTA~;",
        ]
        service, runner = self._service(
            ["UPLOAD_MASTER|ACTIVE|IFLOCREC|3"],
            ["IFLOCREC|OFLOCREC"],
            ["20240517|1|1"],
            ["094512"],
            body_rows,
            ["E|1", "P|2"],
            body_rows,
            ["E|2", "P|1"],
        )

        with self.assertRaisesRegex(
            OutputFileGenerationError,
            "active footer status counts changed",
        ):
            service.generate(self._request(process_ref_no="2309481"))

        self.assertEqual(runner.pending, 0)
        self.assertFalse((self.root / "output").exists())

    def test_oflocrec_rejects_incomplete_footer_status_metadata(self) -> None:
        service, runner = self._service(
            ["UPLOAD_MASTER|ARCHIVE|IFLOCREC|2"],
            ["IFLOCREC|OFLOCREC"],
            ["20240517|1|1"],
            ["094512"],
            [
                "P|BDY;000000001;100;CLP;Y;;;",
                "E|BDY;000000002;200;USD;N;E001;CUENTA~;",
            ],
            ["P|1"],
        )

        with self.assertRaisesRegex(
            OutputFileGenerationError,
            "incomplete footer status metadata",
        ):
            service.generate(self._request(process_ref_no="2309481"))

        self.assertEqual(runner.pending, 0)
        self.assertFalse((self.root / "output").exists())

    def test_oacmclos_archive_2479263_reconstructs_exact_qa_contract(self) -> None:
        processed_rows = [
            _oacmclos_row("P", "999", f"SYN{index:09d}")
            for index in range(1, 957)
        ]
        error_rows = [
            _oacmclos_row(
                "E",
                "999",
                f"SYN{index:09d}",
                "ZZ-SYN001",
            )
            for index in range(957, 1015)
        ]
        service, runner = self._service(
            ["UPLOAD_MASTER|ARCHIVE|IACMCLOS|1014"],
            ["IACMCLOS|OACMCLOS"],
            ["20240131|1|1"],
            ["20260806142355"],
            [*processed_rows, *error_rows],
            [],
            [],
            ["1014|1|1"],
        )

        result = service.generate(self._request(process_ref_no="2479263"))

        self.assertEqual((result.input_code, result.output_code), ("IACMCLOS", "OACMCLOS"))
        self.assertIs(result.source, DataSourceChoice.ARCHIVE)
        self.assertEqual(result.file_date, "20240131")
        self.assertEqual(result.body_count, 1014)
        self.assertEqual(result.status_counts, {"P": 956, "E": 58})
        self.assertEqual(
            result.lines[0],
            "HDR;OACMCLOS_20240131142355;06082026140855;",
        )
        self.assertEqual(result.lines[1], "BDY;999;SYN000000001;Y;;")
        self.assertEqual(
            result.lines[957],
            "BDY;999;SYN000000957;N;ZZ-SYN001;Missing Error Code;",
        )
        self.assertEqual(result.lines[-1], "FTR;956,58,")
        self.assertEqual(result.output_path.name, "OACMCLOS_20240131142355")
        payload = result.output_path.read_bytes()
        self.assertEqual(payload, ("\n".join(result.lines) + "\n").encode("utf-8"))
        self.assertNotIn(b"\r", payload)

        body_script = next(
            script
            for script in runner.scripts
            if "interface_code)) = 'IACMCLOS'" in script
            and "GITA_UPLOAD_MASTER" in script
        )
        self.assertIn("order by record_reference", body_script.lower())
        self.assertNotIn("FN_HANDOFF", body_script.upper())
        self.assertNotIn("GIPKS_", body_script.upper())
        self.assertNotRegex(
            body_script.lower(),
            r"\b(?:insert|update|delete|merge|commit|rollback)\b",
        )
        self.assertEqual(runner.pending, 0)

    def test_oacmclos_non_p_non_null_status_is_rendered_as_unprocessed(self) -> None:
        service, runner = self._service(
            ["UPLOAD_MASTER|ARCHIVE|IACMCLOS|1"],
            ["IACMCLOS|OACMCLOS"],
            ["20240131|1|1"],
            ["20260806142355"],
            [_oacmclos_row("U", "999", "SYN000000001")],
            ["1|1|1"],
        )

        result = service.generate(self._request(process_ref_no="2479263"))

        self.assertEqual(result.status_counts, {"U": 1})
        self.assertEqual(result.lines[1], "BDY;999;SYN000000001;N;;")
        self.assertEqual(result.lines[-1], "FTR;0,1,")
        self.assertEqual(runner.pending, 0)

    def test_oacmclos_active_rows_are_revalidated_before_write(self) -> None:
        initial = [_oacmclos_row("P", "999", "SYN000000001")]
        changed = [
            _oacmclos_row(
                "E",
                "999",
                "SYN000000001",
                "ZZ-SYN001",
            )
        ]
        service, runner = self._service(
            ["UPLOAD_MASTER|ACTIVE|IACMCLOS|1"],
            ["IACMCLOS|OACMCLOS"],
            ["20240131|1|1"],
            ["20260806142355"],
            initial,
            changed,
        )

        with self.assertRaisesRegex(
            OutputFileGenerationError,
            r"active process changed.*retry after processing has finished",
        ):
            service.generate(self._request(process_ref_no="2479263"))

        self.assertFalse((self.root / "output").exists())
        self.assertEqual(runner.pending, 0)

    def test_cladchgo_active_reconstructs_messages_and_revalidates_inputs(self) -> None:
        body_rows = [
            _cladchgo_row("P", "ACC001", "REF001"),
            _cladchgo_row("E", "ACC002", "REF002", "E-ONE;", "ACC002~"),
        ]
        message_rows = [
            _hex("E-ONE") + "|1|" + _hex("Cuenta $1 inválida!")
        ]
        service, runner = self._service(
            ["UPLOAD_MASTER|ACTIVE|CLADCHG|119", "FILE_LOG|ACTIVE|CLADCHG|2"],
            ["CLADCHG|CLADCHGO"],
            ["20260806|1|1"],
            body_rows,
            message_rows,
            body_rows,
            ["20260806|1|1"],
            message_rows,
            ["119|1|1"],
        )

        result = service.generate(self._request(process_ref_no="2806514"))

        self.assertEqual((result.input_code, result.output_code), ("CLADCHG", "CLADCHGO"))
        self.assertIs(result.source, DataSourceChoice.ACTIVE)
        self.assertEqual(result.file_date, "20260806")
        self.assertEqual(result.status_counts, {"P": 1, "E": 1})
        self.assertEqual(
            result.lines,
            (
                "01^20260806",
                "02ACC001^REF001^P^",
                "02ACC002^REF002^E^E-ONE;^Cuenta ACC002 inválida",
                "03^2",
            ),
        )
        self.assertEqual(result.output_path.name, "CLADCHGO_20260806.TXT")
        self.assertEqual(
            result.output_path.read_bytes(),
            ("\n".join(result.lines) + "\n").encode("utf-8"),
        )
        body_scripts = [
            script
            for script in runner.scripts
            if "interface_code)) = 'CLADCHG'" in script
            and "order by record_reference" in script.lower()
        ]
        message_scripts = [
            script for script in runner.scripts if "from ERTB_MSGS" in script
        ]
        self.assertEqual(len(body_scripts), 2)
        self.assertEqual(len(message_scripts), 2)
        self.assertTrue(all("GIPKS_" not in script.upper() for script in body_scripts))
        self.assertEqual(runner.pending, 0)

    def test_cladchgo_archive_uses_gita_and_exact_caret_contract(self) -> None:
        service, runner = self._service(
            ["UPLOAD_MASTER|ARCHIVE|CLADCHG|45", "FILE_LOG|ARCHIVE|CLADCHG|2"],
            ["CLADCHG|CLADCHGO"],
            ["20260805|1|1"],
            [
                _cladchgo_row("P", "ACC010", "REF010"),
                _cladchgo_row("E", "ACC011", "REF011"),
            ],
            ["45|1|1"],
        )

        result = service.generate(self._request(process_ref_no="2806020"))

        self.assertIs(result.source, DataSourceChoice.ARCHIVE)
        self.assertEqual(
            result.lines,
            (
                "01^20260805",
                "02ACC010^REF010^P^",
                "02ACC011^REF011^E^",
                "03^2",
            ),
        )
        body_script = next(
            script
            for script in runner.scripts
            if "interface_code)) = 'CLADCHG'" in script
            and "order by record_reference" in script.lower()
        )
        self.assertIn("from GITA_UPLOAD_MASTER", body_script)
        self.assertEqual(runner.pending, 0)

    def test_cladchgo_rejects_unsupported_status_or_caret_in_source_fields(self) -> None:
        for row, expected in (
            (_cladchgo_row("U", "ACC001", "REF001"), "unsupported statuses"),
            (_cladchgo_row("<NULL>", "ACC001", "REF001"), "unsupported statuses"),
            (_cladchgo_row("P", "ACC^001", "REF001"), "output delimiter"),
            (_cladchgo_row("P", "ACC001", "REF\n001"), "line break"),
        ):
            with self.subTest(expected=expected):
                service, runner = self._service(
                    ["UPLOAD_MASTER|ARCHIVE|CLADCHG|1"],
                    ["CLADCHG|CLADCHGO"],
                    ["20260805|1|1"],
                    [row],
                )

                with self.assertRaisesRegex(OutputFileGenerationError, expected):
                    service.generate(self._request(process_ref_no="2806020"))

                self.assertFalse((self.root / "output").exists())
                self.assertEqual(runner.pending, 0)

    def test_cladchgo_rejects_caret_or_newline_in_rendered_message(self) -> None:
        for message in ("Cuenta ^ inválida", "Cuenta\ninválida"):
            with self.subTest(message=message):
                service, runner = self._service(
                    ["UPLOAD_MASTER|ARCHIVE|CLADCHG|1"],
                    ["CLADCHG|CLADCHGO"],
                    ["20260805|1|1"],
                    [_cladchgo_row("E", "ACC001", "REF001", "E-ONE;")],
                    [_hex("E-ONE") + "|1|" + _hex(message)],
                )

                with self.assertRaisesRegex(
                    OutputFileGenerationError,
                    r"CLADCHGO error description.*delimiter.*line break",
                ):
                    service.generate(self._request(process_ref_no="2806020"))

                self.assertFalse((self.root / "output").exists())
                self.assertEqual(runner.pending, 0)

    def test_ofcrelvp_archive_reconstructs_exact_qa_contract(self) -> None:
        service, runner = self._service(
            ["UPLOAD_MASTER|ARCHIVE|IFCRELVP|4561"],
            ["IFCRELVP|OFCRELVP"],
            ["20240809|1|1"],
            [
                _ofcrelvp_row("P", "001", "123456789", "ESN-1"),
                _ofcrelvp_row(
                    "E",
                    "002",
                    "987654321",
                    "ESN-2",
                    "E001",
                    "PARAM",
                ),
            ],
            ["4561|1|1"],
            ["142355"],
        )

        result = service.generate(self._request(process_ref_no="2513888"))

        self.assertEqual((result.input_code, result.output_code), ("IFCRELVP", "OFCRELVP"))
        self.assertIs(result.source, DataSourceChoice.ARCHIVE)
        self.assertEqual(result.file_date, "20240809")
        self.assertEqual(result.status_counts, {"P": 1, "E": 1})
        self.assertEqual(
            result.lines,
            (
                "LH^20240809",
                "BH^001^123456789^ESN-1^Y",
                "BH^002^987654321^ESN-2^E001^PARAM",
                "LF^1^1^2",
            ),
        )
        self.assertEqual(
            result.output_path.name,
            "OFCRELVP_09082024_142355.TXT",
        )
        payload = result.output_path.read_bytes()
        self.assertEqual(payload, ("\n".join(result.lines) + "\n").encode("utf-8"))
        self.assertNotIn(b"\r", payload)
        time_scripts = [
            script for script in runner.scripts if "to_char(sysdate" in script.lower()
        ]
        self.assertEqual(len(time_scripts), 1)
        self.assertIn("to_char(sysdate, 'HH24MISS')", time_scripts[0])
        body_script = next(
            script
            for script in runner.scripts
            if "interface_code)) = 'IFCRELVP'" in script
            and "order by record_reference" in script.lower()
        )
        self.assertNotIn("FN_HANDOFF", body_script.upper())
        self.assertNotIn("GIPKS_", body_script.upper())
        self.assertEqual(runner.pending, 0)

    def test_ofcrelvp_rejects_u_null_or_other_status_before_clock_and_write(self) -> None:
        for status in ("U", "<NULL>", "X"):
            with self.subTest(status=status):
                service, runner = self._service(
                    ["UPLOAD_MASTER|ARCHIVE|IFCRELVP|1"],
                    ["IFCRELVP|OFCRELVP"],
                    ["20240809|1|1"],
                    [_ofcrelvp_row(status, "001", "123", "ESN")],
                )

                with self.assertRaisesRegex(
                    OutputFileGenerationError,
                    r"IFCRELVP contains unsupported statuses",
                ):
                    service.generate(self._request(process_ref_no="2554008"))

                self.assertFalse(
                    any("to_char(sysdate" in script.lower() for script in runner.scripts)
                )
                self.assertFalse((self.root / "output").exists())
                self.assertEqual(runner.pending, 0)

    def test_ofcrelvp_rejects_caret_or_newline_in_hex_transported_fields(self) -> None:
        for account in ("123^456", "123\n456"):
            with self.subTest(account=account):
                service, runner = self._service(
                    ["UPLOAD_MASTER|ARCHIVE|IFCRELVP|1"],
                    ["IFCRELVP|OFCRELVP"],
                    ["20240809|1|1"],
                    [_ofcrelvp_row("P", "001", account, "ESN")],
                )

                with self.assertRaisesRegex(
                    OutputFileGenerationError,
                    r"OFCRELVP body field.*delimiter.*line break",
                ):
                    service.generate(self._request(process_ref_no="2513888"))

                self.assertFalse((self.root / "output").exists())
                self.assertEqual(runner.pending, 0)

    def test_oficowcg_active_reconstructs_header_body_errors_and_footer(self) -> None:
        processed_fields = (
            "XREF-1", "10", "001", "20260806", "BANK", "ACCOUNT-1",
            "INSTR-1", "INSTR-2", "SEC", "100.25", "C",
        )
        error_fields = (
            "XREF-2", "20", "001", "20260806", "BANK", "ACCOUNT-2",
            "INSTR-3", "INSTR-4", "SEC", "200", "C",
        )
        unprocessed_fields = (
            "XREF-3", "30", "001", "20260806", "BANK", "ACCOUNT-3",
            "INSTR-5", "INSTR-6", "SEC", "300", "C",
        )
        service, runner = self._service(
            ["UPLOAD_MASTER|ACTIVE|IFICOWCG|3"],
            ["IFICOWCG|OFICOWCG"],
            ["20260806|1|1"],
            ["1|" + _hex("IFICOWCG_OP_20260806.TXT")],
            [
                _oficowcg_row("P", processed_fields),
                _oficowcg_row(
                    "E", error_fields, error_code="E-ONE", error_params="20~"
                ),
                _oficowcg_row(
                    "U",
                    unprocessed_fields,
                    error_code="GI-INT214",
                    error_params="XREF-3~",
                ),
            ],
            [_oficowcg_coverage(3)],
            [
                _hex("E-ONE") + "|1|" + _hex("Cuenta $1 inválida!"),
                _hex("GI-INT214") + "|1|" + _hex("Registro $1 pendiente!"),
            ],
            [_oficowcg_coverage(3)],
            [
                _oficowcg_row("P", processed_fields),
                _oficowcg_row(
                    "E", error_fields, error_code="E-ONE", error_params="20~"
                ),
                _oficowcg_row(
                    "U",
                    unprocessed_fields,
                    error_code="GI-INT214",
                    error_params="XREF-3~",
                ),
            ],
            ["20260806|1|1"],
            ["1|" + _hex("IFICOWCG_OP_20260806.TXT")],
            [
                _hex("E-ONE") + "|1|" + _hex("Cuenta $1 inválida!"),
                _hex("GI-INT214") + "|1|" + _hex("Registro $1 pendiente!"),
            ],
            ["3|1|1"],
        )

        result = service.generate(self._request(process_ref_no="2806536"))

        self.assertEqual((result.input_code, result.output_code), ("IFICOWCG", "OFICOWCG"))
        self.assertIs(result.source, DataSourceChoice.ACTIVE)
        self.assertEqual(result.file_date, "20260806")
        self.assertEqual(result.status_counts, {"P": 1, "E": 1, "U": 1})
        self.assertEqual(
            result.lines,
            (
                "HDR;IFICOWCG_OP_20260806.TXT;20260806;",
                "BDY;" + ";".join(processed_fields) + ";P;",
                "BDY;" + ";".join(error_fields) + ";E;E-ONE;Cuenta 20 inválida;",
                "BDY;" + ";".join(unprocessed_fields) + ";U;GI-INT214;Registro XREF-3 pendiente;",
                "FTR;1;2;",
            ),
        )
        self.assertEqual(result.output_path.name, "OFICOWCG_20260806.TXT")
        self.assertTrue(
            any("from GITB_FILE_MASTER" in script for script in runner.scripts)
        )
        body_script = next(
            script
            for script in runner.scripts
            if "from GITU_UPLOAD_MASTER giu" in script
        )
        self.assertIn("GITM_CLEARING_LOG", body_script)
        self.assertIn("IFTB_CLEARING_UPLOAD", body_script)
        self.assertNotIn("FN_HANDOFF", body_script.upper())
        self.assertNotIn("GIPKS_", body_script.upper())
        self.assertEqual(runner.pending, 0)

    def test_oficowcg_colombia_active_runs_the_full_country_contract(self) -> None:
        success_fields = (
            "XREF-1", "10", "001", "20260604", "BANK", "ACCOUNT-1",
            "INSTR-1", "INSTR-2", "SEC", "100.25", "C",
        )
        rejected_fields = (
            "XREF-2", "20", "002", "20260604", "BANK", "ACCOUNT-2",
            "INSTR-3", "INSTR-4", "SEC", "200", "C",
        )
        body_rows = [
            _oficowcg_colombia_row("P", success_fields, "SUCC"),
            _oficowcg_colombia_row(
                "P",
                rejected_fields,
                "REJR",
                error_code="R-ONE",
                error_params="XREF-2~",
            ),
        ]
        coverage = ["2|2|2|2|0|2|0|0"]
        message_rows = [
            _hex("R-ONE") + "|1|" + _hex("Documento $1 rechazado!")
        ]
        service, runner = self._service(
            ["UPLOAD_MASTER|ACTIVE|IFICOWCG|2"],
            ["IFICOWCG|OFICOWCG"],
            ["20260604|1|1"],
            ["1|" + _hex("IFICOWCG_20260604.TXT")],
            body_rows,
            coverage,
            message_rows,
            coverage,
            body_rows,
            ["20260604|1|1"],
            ["1|" + _hex("IFICOWCG_20260604.TXT")],
            message_rows,
            ["2|1|1"],
        )
        credential = dict(
            self.config.credential,
            tns="BFCO_POCISANTIAGO",
        )
        self.config.credentials["colombia"] = {
            "CO-PROD-DB": {"CO-SHARED-PROD": credential}
        }
        target = OracleTarget(
            country="colombia",
            database_key="co-prod-db",
            credential_key="co-shared-prod",
            tns="BFCO_POCISANTIAGO",
            label="Colombia PROD Santiago",
        )

        result = service.generate(
            GenerationRequest(target=target, process_ref_no="5328716")
        )

        self.assertEqual((result.input_code, result.output_code), ("IFICOWCG", "OFICOWCG"))
        self.assertIs(result.source, DataSourceChoice.ACTIVE)
        self.assertEqual(result.status_counts, {"P": 2})
        self.assertEqual(
            result.lines,
            (
                "HDR;IFICOWCG_20260604.TXT;20260604;",
                "BDY;" + ";".join(success_fields) + ";P;SUCC;",
                "BDY;"
                + ";".join(rejected_fields)
                + ";P;R-ONE;Documento XREF-2 rechazado;REJR;",
                "FTR;2;0;",
            ),
        )
        self.assertEqual(result.output_path.parent.name, "Colombia")
        self.assertEqual(result.output_path.name, "OFICOWCG_20260604.TXT")
        body_script = next(
            script
            for script in runner.scripts
            if "CSTB_CLEARING_REJECTION" in script
            and "rawtohex" in script.lower()
        )
        self.assertIn("IFTB_CLEARING_UPLOAD_C", body_script)
        self.assertNotIn("FN_HANDOFF", body_script.upper())
        self.assertEqual(runner.pending, 0)

    def test_colombia_connection_error_restarts_generation_on_sao_paulo(self) -> None:
        success_fields = (
            "XREF-1", "10", "001", "20260604", "BANK", "ACCOUNT-1",
            "INSTR-1", "INSTR-2", "SEC", "100.25", "C",
        )
        body_rows = [_oficowcg_colombia_row("P", success_fields, "SUCC")]
        coverage = ["1|1|1|1|0|1|0|0"]
        service, runner = self._service(
            RunResult(1, "", "ORA-12541: TNS:no listener"),
            ["UPLOAD_MASTER|ACTIVE|IFICOWCG|1"],
            ["IFICOWCG|OFICOWCG"],
            ["20260604|1|1"],
            ["1|" + _hex("IFICOWCG_20260604.TXT")],
            body_rows,
            coverage,
            coverage,
            body_rows,
            ["20260604|1|1"],
            ["1|" + _hex("IFICOWCG_20260604.TXT")],
            ["1|1|1"],
        )
        primary_credential = {
            **self.config.credential,
            "tns": "BFCO_POCISANTIAGO",
        }
        fallback_credential = {
            **self.config.credential,
            "user": "sao_user",
            "tns": "BFCO_POCISAOPALO",
        }
        self.config.credentials["colombia"] = {
            "CO-SANTIAGO": {"CO-SHARED-PROD": primary_credential},
            "CO-SAO-PAULO": {"CO-SHARED-PROD": fallback_credential},
        }
        target = OracleTarget(
            country="colombia",
            database_key="co-santiago",
            credential_key="co-shared-prod",
            tns="BFCO_POCISANTIAGO",
            label="Colombia PROD Santiago",
        )

        with self.assertLogs(
            "features.output_file_generation.service",
            level="INFO",
        ) as captured:
            result = service.generate(
                GenerationRequest(
                    target=target,
                    process_ref_no="5328716",
                    interface_code="OFICOWCG",
                )
            )

        primary = "fake_user/fake-password@BFCO_POCISANTIAGO"
        fallback = "sao_user/fake-password@BFCO_POCISAOPALO"
        self.assertEqual(runner.connections, [primary, *([fallback] * 11)])
        self.assertEqual(result.output_code, "OFICOWCG")
        self.assertEqual(result.output_path.parent.name, "Colombia")
        self.assertEqual(runner.pending, 0)
        logs = "\n".join(captured.output)
        self.assertIn("BFCO_POCISAOPALO", logs)
        self.assertIn("Output reconstruction completed", logs)
        self.assertIn("tns=BFCO_POCISAOPALO", logs)

    def test_oficowcg_colombia_empty_clearing_cursor_reports_cleanup(self) -> None:
        service, runner = self._service(
            ["UPLOAD_MASTER|ACTIVE|IFICOWCG|30"],
            ["IFICOWCG|OFICOWCG"],
            ["20260604|1|1"],
            ["1|" + _hex("IFICOWCG_20260604.TXT")],
            [],
        )
        credential = dict(
            self.config.credential,
            tns="BFCO_POCISANTIAGO",
        )
        self.config.credentials["colombia"] = {
            "CO-PROD-DB": {"CO-SHARED-PROD": credential}
        }
        target = OracleTarget(
            country="colombia",
            database_key="co-prod-db",
            credential_key="co-shared-prod",
            tns="BFCO_POCISANTIAGO",
            label="Colombia PROD Santiago",
        )

        with self.assertRaises(OutputFileGenerationError) as raised:
            service.generate(
                GenerationRequest(target=target, process_ref_no="5328716")
            )

        message = str(raised.exception)
        self.assertIn("Colombia OFICOWCG has no clearing output rows", message)
        self.assertIn("GITM_CLEARING_LOG", message)
        self.assertIn("IFTB_CLEARING_UPLOAD", message)
        self.assertIn("IFTB_CLEARING_UPLOAD_C", message)
        self.assertIn("cleaned up", message)
        for state in ("SUCC", "ERRO", "REJR"):
            self.assertIn(state, message)
        self.assertIn("generation was stopped", message)
        self.assertEqual(len(runner.scripts), 5)
        self.assertEqual(runner.pending, 0)
        self.assertFalse((self.root / "output").exists())

    def test_oficowcg_partial_clearing_coverage_never_creates_a_file(self) -> None:
        fields = (
            "XREF-1", "10", "001", "20260806", "BANK", "ACCOUNT-1",
            "INSTR-1", "INSTR-2", "SEC", "100.25", "C",
        )
        service, runner = self._service(
            ["UPLOAD_MASTER|ACTIVE|IFICOWCG|2"],
            ["IFICOWCG|OFICOWCG"],
            ["20260806|1|1"],
            ["1|" + _hex("IFICOWCG_OP_20260806.TXT")],
            [_oficowcg_row("P", fields)],
            [_oficowcg_coverage(2, one_output=1, no_output=1)],
        )

        with self.assertRaisesRegex(
            OutputFileGenerationError,
            r"Each IFICOWCG upload row must resolve exactly one pre-UNION.*"
            r"missing or duplicated output",
        ):
            service.generate(self._request(process_ref_no="2806536"))

        self.assertEqual(len(runner.scripts), 6)
        self.assertFalse((self.root / "output").exists())
        self.assertEqual(runner.pending, 0)

    def test_oficowcg_equal_counts_do_not_hide_missing_and_orphan_rows(self) -> None:
        first_fields = (
            "XREF-1", "10", "001", "20260806", "BANK", "ACCOUNT-1",
            "INSTR-1", "INSTR-2", "SEC", "100.25", "C",
        )
        orphan_fields = (
            "XREF-X", "90", "001", "20260806", "BANK", "ACCOUNT-X",
            "INSTR-X", "INSTR-Y", "SEC", "900", "C",
        )
        service, runner = self._service(
            ["UPLOAD_MASTER|ACTIVE|IFICOWCG|2"],
            ["IFICOWCG|OFICOWCG"],
            ["20260806|1|1"],
            ["1|" + _hex("IFICOWCG_OP_20260806.TXT")],
            [
                _oficowcg_row("P", first_fields),
                _oficowcg_row("P", orphan_fields),
            ],
            [_oficowcg_coverage(2, one_output=1, no_output=1, orphan_branch_b=1)],
        )

        with self.assertRaisesRegex(
            OutputFileGenerationError,
            r"Each IFICOWCG upload row must resolve exactly one pre-UNION.*"
            r"missing or duplicated output",
        ):
            service.generate(self._request(process_ref_no="2806536"))

        self.assertEqual(len(runner.scripts), 6)
        self.assertFalse((self.root / "output").exists())
        self.assertEqual(runner.pending, 0)

    def test_oficowcg_equal_counts_do_not_hide_duplicated_upload_output(self) -> None:
        first_fields = (
            "XREF-1", "10", "001", "20260806", "BANK", "ACCOUNT-1",
            "INSTR-1", "INSTR-2", "SEC", "100.25", "C",
        )
        duplicate_fields = (
            "XREF-2", "20", "001", "20260806", "BANK", "ACCOUNT-2",
            "INSTR-3", "INSTR-4", "SEC", "200", "C",
        )
        service, runner = self._service(
            ["UPLOAD_MASTER|ACTIVE|IFICOWCG|2"],
            ["IFICOWCG|OFICOWCG"],
            ["20260806|1|1"],
            ["1|" + _hex("IFICOWCG_OP_20260806.TXT")],
            [
                _oficowcg_row("P", first_fields),
                _oficowcg_row("P", duplicate_fields),
            ],
            [_oficowcg_coverage(2, one_output=0, no_output=1, multiple_outputs=1)],
        )

        with self.assertRaisesRegex(
            OutputFileGenerationError,
            r"Each IFICOWCG upload row must resolve exactly one pre-UNION.*"
            r"missing or duplicated output",
        ):
            service.generate(self._request(process_ref_no="2806536"))

        self.assertEqual(len(runner.scripts), 6)
        self.assertFalse((self.root / "output").exists())
        self.assertEqual(runner.pending, 0)

    def test_oficowcg_rejects_duplicate_upload_record_references(self) -> None:
        first_fields = (
            "XREF-1", "10", "001", "20260806", "BANK", "ACCOUNT-1",
            "INSTR-1", "INSTR-2", "SEC", "100.25", "C",
        )
        second_fields = (
            "XREF-2", "20", "001", "20260806", "BANK", "ACCOUNT-2",
            "INSTR-3", "INSTR-4", "SEC", "200", "C",
        )
        service, runner = self._service(
            ["UPLOAD_MASTER|ACTIVE|IFICOWCG|2"],
            ["IFICOWCG|OFICOWCG"],
            ["20260806|1|1"],
            ["1|" + _hex("IFICOWCG_OP_20260806.TXT")],
            [
                _oficowcg_row("P", first_fields),
                _oficowcg_row("P", second_fields),
            ],
            [_oficowcg_coverage(2, distinct_refs=1)],
        )

        with self.assertRaisesRegex(
            OutputFileGenerationError,
            r"RECORD_REFERENCE values must be non-null and unique",
        ):
            service.generate(self._request(process_ref_no="2806536"))

        self.assertEqual(len(runner.scripts), 6)
        self.assertFalse((self.root / "output").exists())
        self.assertEqual(runner.pending, 0)

    def test_oficowcg_union_collision_never_creates_a_partial_file(self) -> None:
        fields = (
            "XREF-1", "10", "001", "20260806", "BANK", "ACCOUNT-1",
            "INSTR-1", "INSTR-2", "SEC", "100.25", "C",
        )
        service, runner = self._service(
            ["UPLOAD_MASTER|ACTIVE|IFICOWCG|2"],
            ["IFICOWCG|OFICOWCG"],
            ["20260806|1|1"],
            ["1|" + _hex("IFICOWCG_OP_20260806.TXT")],
            [_oficowcg_row("P", fields)],
            [_oficowcg_coverage(2)],
        )

        with self.assertRaisesRegex(
            OutputFileGenerationError,
            r"QA UNION collapsed or changed rows.*one row per IFICOWCG upload",
        ):
            service.generate(self._request(process_ref_no="2806536"))

        self.assertEqual(len(runner.scripts), 6)
        self.assertFalse((self.root / "output").exists())
        self.assertEqual(runner.pending, 0)

    def test_oficowcg_identity_change_aborts_before_saving(self) -> None:
        fields = (
            "XREF-1", "10", "001", "20260806", "BANK", "ACCOUNT-1",
            "INSTR-1", "INSTR-2", "SEC", "100.25", "C",
        )
        service, runner = self._service(
            ["UPLOAD_MASTER|ACTIVE|IFICOWCG|1"],
            ["IFICOWCG|OFICOWCG"],
            ["20260806|1|1"],
            ["1|" + _hex("IFICOWCG_OP_20260806.TXT")],
            [_oficowcg_row("P", fields)],
            [_oficowcg_coverage(1)],
            [_oficowcg_coverage(1, one_gic=0, one_output=0, no_output=1)],
        )

        with self.assertRaisesRegex(
            OutputFileGenerationError,
            r"identity coverage changed.*generation was stopped",
        ):
            service.generate(self._request(process_ref_no="2806536"))

        self.assertEqual(len(runner.scripts), 7)
        self.assertFalse((self.root / "output").exists())
        self.assertEqual(runner.pending, 0)

    def test_active_process_change_aborts_without_saving(self) -> None:
        initial_body = ["P|BDY;000000001;100;CLP;BLOQUEO;Y;;;"]
        changed_body = [
            "P|BDY;000000001;100;CLP;BLOQUEO;Y;;;",
            "E|BDY;000000002;200;CLP;BLOQUEO;N;E001;Bloqueo;",
        ]
        service, runner = self._service(
            ["UPLOAD_MASTER|ACTIVE|ACCBLOCK|1"],
            ["ACCBLOCK|ACCBLKOU"],
            ["20260730|1|1"],
            ["142355"],
            initial_body,
            changed_body,
        )

        with self.assertRaisesRegex(
            OutputFileGenerationError,
            r"active process changed.*retry after processing has finished",
        ):
            service.generate(self._request())

        self.assertEqual(runner.pending, 0)
        self.assertFalse((self.root / "output").exists())

    def test_final_upload_recheck_aborts_if_rows_changed_or_were_purged(self) -> None:
        service, runner = self._service(
            ["UPLOAD_MASTER|ARCHIVE|IFDOBIEL|2"],
            ["IFDOBIEL|OFDOBIEL"],
            ["20260731|1|1"],
            ["P|||BDY;C;000000001;E;P;"],
            ["1|1|1"],
        )

        with self.assertRaisesRegex(
            OutputFileGenerationError,
            r"upload rows changed or were purged.*retry",
        ):
            service.generate(self._request())

        self.assertEqual(runner.pending, 0)
        self.assertFalse((self.root / "output").exists())

    def test_final_mapping_recheck_aborts_if_definition_changed(self) -> None:
        service, runner = self._service(
            ["UPLOAD_MASTER|ARCHIVE|IFDOBIEL|1"],
            ["IFDOBIEL|OFDOBIEL"],
            ["20260731|1|1"],
            ["P|||BDY;C;000000001;E;P;"],
            ["1|2|1"],
        )

        with self.assertRaisesRegex(
            OutputFileGenerationError,
            r"output mapping changed.*stopped before saving",
        ):
            service.generate(self._request())

        self.assertEqual(runner.pending, 0)
        self.assertFalse((self.root / "output").exists())

    def test_oficowcg_archive_fails_before_unverified_sources_are_queried(self) -> None:
        colombia_credential = {
            **self.config.credential,
            "tns": "BFCO_POCISANTIAGO",
        }
        self.config.credentials["colombia"] = {
            "CO-PROD-DB": {"CO-SHARED-PROD": colombia_credential}
        }
        self.target = OracleTarget(
            country="colombia",
            database_key="co-prod-db",
            credential_key="co-shared-prod",
            tns="BFCO_POCISANTIAGO",
            label="Colombia PROD Santiago",
        )
        service, runner = self._service(
            ["UPLOAD_MASTER|ARCHIVE|IFICOWCG|114"],
            ["IFICOWCG|OFICOWCG"],
        )

        with self.assertRaisesRegex(
            OutputFileGenerationError,
            r"archive upload rows were found.*GITM_CLEARING_LOG.*"
            r"IFTB_CLEARING_UPLOAD.*GITB_FILE_MASTER.*empty output",
        ):
            service.generate(self._request(process_ref_no="5328716"))

        self.assertEqual(len(runner.scripts), 2)
        self.assertEqual(runner.pending, 0)

    def test_non_chile_generation_requires_its_matching_qa_contract(self) -> None:
        colombia_credential = {
            **self.config.credential,
            "tns": "BFCO_POCISANTIAGO",
        }
        self.config.credentials["colombia"] = {
            "CO-PROD-DB": {"CO-SHARED-PROD": colombia_credential}
        }
        self.target = OracleTarget(
            country="colombia",
            database_key="co-prod-db",
            credential_key="co-shared-prod",
            tns="BFCO_POCISANTIAGO",
            label="Colombia PROD Santiago",
        )
        service, runner = self._service(
            ["UPLOAD_MASTER|ACTIVE|ACCBLOCK|1"],
            ["ACCBLOCK|ACCBLKOU"],
        )

        with self.assertRaisesRegex(
            OutputFileGenerationError,
            r"ACCBLKOU generation for Colombia is not enabled yet.*"
            r"GIPKS_ACCBLKOU.*Colombia QA.*Chile QA contract",
        ):
            service.generate(self._request(process_ref_no="5328716"))

        self.assertEqual(len(runner.scripts), 2)
        self.assertEqual(runner.pending, 0)

    def test_oficowcg_empty_clearing_cursor_never_creates_a_file(self) -> None:
        service, runner = self._service(
            ["UPLOAD_MASTER|ACTIVE|IFICOWCG|30"],
            ["IFICOWCG|OFICOWCG"],
            ["20260806|1|1"],
            ["1|" + _hex("IFICOWCG_OP_20260806.TXT")],
            [],
        )

        with self.assertRaisesRegex(
            OutputFileGenerationError,
            r"no reconstructible clearing output rows.*GITM_CLEARING_LOG.*"
            r"IFTB_CLEARING_UPLOAD.*empty output",
        ):
            service.generate(self._request(process_ref_no="5328716"))

        self.assertEqual(len(runner.scripts), 5)
        self.assertFalse((self.root / "output").exists())
        self.assertEqual(runner.pending, 0)

    def test_oficowcg_ambiguous_physical_filename_aborts_before_body(self) -> None:
        service, runner = self._service(
            ["UPLOAD_MASTER|ACTIVE|IFICOWCG|30"],
            ["IFICOWCG|OFICOWCG"],
            ["20260806|1|1"],
            ["2|" + _hex("IFICOWCG_OP_20260806.TXT")],
        )

        with self.assertRaisesRegex(
            OutputFileGenerationError,
            r"More than one physical input filename.*ambiguous",
        ):
            service.generate(self._request(process_ref_no="2806536"))

        self.assertEqual(len(runner.scripts), 4)
        self.assertFalse((self.root / "output").exists())
        self.assertEqual(runner.pending, 0)

    def test_interface_pair_is_detected_only_from_process_records(self) -> None:
        service, runner = self._service(
            ["UPLOAD_MASTER|ARCHIVE|IFDOBIEL|1"],
            ["IFDOBIEL|OFDOBIEL"],
            ["20260731|1|1"],
            ["P|||BDY;C;000000001;E;P;"],
            ["1|1|1"],
        )

        result = service.generate(self._request())

        self.assertEqual((result.input_code, result.output_code), ("IFDOBIEL", "OFDOBIEL"))
        self.assertTrue(any("= 'IFDOBIEL'" in script for script in runner.scripts))
        self.assertEqual(runner.pending, 0)

    def test_mapping_mismatch_stops_before_body_query(self) -> None:
        service, runner = self._service(
            ["UPLOAD_MASTER|ACTIVE|ACCBLOCK|1"],
            ["ACCBLOCK|WRONGOUT"],
        )

        with self.assertRaisesRegex(
            OutputFileGenerationError,
            r"Oracle does not confirm ACCBLOCK->ACCBLKOU",
        ):
            service.generate(self._request())

        self.assertEqual(len(runner.scripts), 2)
        self.assertEqual(runner.pending, 0)
        self.assertFalse((self.root / "output").exists())

    def test_multiple_outgoing_mappings_abort_automatic_generation(self) -> None:
        service, runner = self._service(
            ["UPLOAD_MASTER|ACTIVE|ACCBLOCK|1"],
            ["ACCBLOCK|ACCBLKOU", "ACCBLOCK|ANOTHEROUT"],
        )

        with self.assertRaisesRegex(
            OutputFileGenerationError,
            r"more than one outgoing interface.*ACCBLOCK->ACCBLKOU",
        ):
            service.generate(self._request())

        self.assertEqual(len(runner.scripts), 2)
        self.assertEqual(runner.pending, 0)
        self.assertFalse((self.root / "output").exists())

    def test_auto_source_rejects_active_and_archive_ambiguity(self) -> None:
        service, runner = self._service(
            [
                "UPLOAD_MASTER|ACTIVE|IFDOBIEL|2",
                "UPLOAD_MASTER|ARCHIVE|IFDOBIEL|2",
            ],
            ["IFDOBIEL|OFDOBIEL"],
        )

        with self.assertRaisesRegex(
            OutputFileGenerationError,
            "exists in active and archived data",
        ):
            service.generate(self._request())

        self.assertEqual(len(runner.scripts), 2)
        self.assertEqual(runner.pending, 0)

    def test_auto_interface_rejects_multiple_supported_pairs(self) -> None:
        service, runner = self._service(
            [
                "UPLOAD_MASTER|ARCHIVE|IFDOBIEL|1",
                "UPLOAD_MASTER|ARCHIVE|ACCBLOCK|1",
            ],
            ["ACCBLOCK|ACCBLKOU", "IFDOBIEL|OFDOBIEL"],
        )

        with self.assertRaisesRegex(
            OutputFileGenerationError,
            "more than one supported interface",
        ):
            service.generate(self._request())

        self.assertEqual(len(runner.scripts), 2)
        self.assertEqual(runner.pending, 0)

    def test_manual_interface_selects_one_supported_event_from_shared_process(self) -> None:
        service, runner = self._service(
            [
                "UPLOAD_MASTER|ARCHIVE|IFDOBIEL|1",
                "UPLOAD_MASTER|ARCHIVE|ACCBLOCK|1",
            ],
            ["IFDOBIEL|OFDOBIEL"],
            ["20260731|1|1"],
            ["P|||BDY;C;000000001;E;P;"],
            ["1|1|1"],
        )

        result = service.generate(self._request(interface_code="OFDOBIEL"))

        self.assertEqual((result.input_code, result.output_code), ("IFDOBIEL", "OFDOBIEL"))
        discovery_script = runner.scripts[0]
        self.assertEqual(
            discovery_script.count(
                "upper(trim(interface_code)) = 'IFDOBIEL'"
            ),
            4,
        )
        self.assertNotIn("group by upper(trim(interface_code))", discovery_script.lower())
        mapping_script = runner.scripts[1]
        self.assertIn("in ('IFDOBIEL')", mapping_script)
        self.assertNotIn("'ACCBLOCK'", mapping_script)
        self.assertEqual(runner.pending, 0)

    def test_manual_interface_ignores_unselected_unsupported_event(self) -> None:
        service, runner = self._service(
            [
                "UPLOAD_MASTER|ARCHIVE|IFDOBIEL|1",
                "UPLOAD_MASTER|ARCHIVE|NOTREADY|9",
            ],
            ["IFDOBIEL|OFDOBIEL"],
            ["20260731|1|1"],
            ["P|||BDY;C;000000001;E;P;"],
            ["1|1|1"],
        )

        result = service.generate(self._request(interface_code="IFDOBIEL"))

        self.assertEqual(result.output_code, "OFDOBIEL")
        self.assertEqual(runner.pending, 0)

    def test_manual_interface_must_exist_for_the_selected_process(self) -> None:
        service, runner = self._service(
            ["UPLOAD_MASTER|ARCHIVE|ACCBLOCK|1"],
        )

        with self.assertRaisesRegex(
            OutputFileGenerationError,
            r"selected interface IFDOBIEL.*was not found",
        ):
            service.generate(self._request(interface_code="OFDOBIEL"))

        self.assertEqual(len(runner.scripts), 1)
        self.assertEqual(runner.pending, 0)

    def test_manual_interface_keeps_active_archive_ambiguity_fail_closed(self) -> None:
        service, runner = self._service(
            [
                "UPLOAD_MASTER|ACTIVE|IFDOBIEL|1",
                "UPLOAD_MASTER|ARCHIVE|IFDOBIEL|1",
            ],
        )

        with self.assertRaisesRegex(
            OutputFileGenerationError,
            r"selected interface IFDOBIEL exists in active and archived data",
        ):
            service.generate(self._request(interface_code="IFDOBIEL"))

        self.assertEqual(len(runner.scripts), 1)
        self.assertEqual(runner.pending, 0)

    def test_invalid_manual_interface_fails_before_sql(self) -> None:
        service, runner = self._service()

        with self.assertRaisesRegex(
            OutputFileGenerationError,
            "selected interface/output is not supported",
        ):
            service.generate(self._request(interface_code="NOT_IMPLEMENTED"))

        self.assertEqual(runner.scripts, [])

    def test_invalid_expected_input_date_fails_before_sql(self) -> None:
        service, runner = self._service()
        request = replace(
            self._request(interface_code="OFDOBIEL"),
            input_file_date="20260230",
        )

        with self.assertRaisesRegex(
            OutputFileGenerationError,
            "valid calendar date",
        ):
            service.generate(request)

        self.assertEqual(runner.scripts, [])

    def test_expected_input_date_must_match_prod_file_log(self) -> None:
        service, runner = self._service(
            ["UPLOAD_MASTER|ARCHIVE|IFDOBIEL|1"],
            ["IFDOBIEL|OFDOBIEL"],
            ["20260731|1|1"],
        )
        request = replace(
            self._request(interface_code="OFDOBIEL"),
            input_file_date="20260801",
        )

        with self.assertRaisesRegex(
            OutputFileGenerationError,
            r"selected input date does not match.*selected 01-08-2026.*detected 31-07-2026",
        ):
            service.generate(request)

        self.assertEqual(len(runner.scripts), 3)
        self.assertFalse((self.root / "output").exists())

    def test_expected_input_date_is_validated_but_never_overrides_oracle(self) -> None:
        service, runner = self._service(
            ["UPLOAD_MASTER|ARCHIVE|IFDOBIEL|1"],
            ["IFDOBIEL|OFDOBIEL"],
            ["20260731|1|1"],
            ["P|||BDY;C;000000001;E;P;"],
            ["1|1|1"],
        )
        request = replace(
            self._request(interface_code="OFDOBIEL"),
            input_file_date="20260731",
        )

        result = service.generate(request)

        self.assertEqual(result.file_date, "20260731")
        self.assertEqual(result.output_path.name, "OFDOBIEL_20260731.TXT")
        self.assertTrue(
            any("from GITA_FILE_LOG" in script for script in runner.scripts)
        )
        self.assertEqual(runner.pending, 0)

    def test_manual_shared_process_blocks_process_global_footer_contract(self) -> None:
        service, runner = self._service(
            [
                "UPLOAD_MASTER|ACTIVE|STDINRTS|1",
                "UPLOAD_MASTER|ACTIVE|IFDOBIEL|1",
            ],
        )

        with self.assertRaisesRegex(
            OutputFileGenerationError,
            r"STDINROU cannot safely isolate this shared process.*IFDOBIEL",
        ):
            service.generate(self._request(interface_code="STDINROU"))

        self.assertEqual(len(runner.scripts), 1)
        self.assertEqual(runner.pending, 0)

    def test_stale_archive_log_does_not_hide_current_upload_source(self) -> None:
        body = ["P|||BDY;C;000000001;E;P;"]
        service, runner = self._service(
            [
                "UPLOAD_MASTER|ACTIVE|IFDOBIEL|1",
                "FILE_LOG|ARCHIVE|IFDOBIEL|2",
            ],
            ["IFDOBIEL|OFDOBIEL"],
            ["20260731|1|1"],
            body,
            body,
            ["20260731|1|1"],
            ["1|1|1"],
        )

        result = service.generate(self._request())

        self.assertIs(result.source, DataSourceChoice.ACTIVE)
        self.assertEqual((result.input_code, result.output_code), ("IFDOBIEL", "OFDOBIEL"))
        self.assertEqual(runner.pending, 0)

    def test_stale_log_for_another_supported_interface_is_not_ambiguous(self) -> None:
        service, runner = self._service(
            [
                "UPLOAD_MASTER|ARCHIVE|IFDOBIEL|1",
                "FILE_LOG|ARCHIVE|ACCBLOCK|1",
            ],
            ["ACCBLOCK|ACCBLKOU", "IFDOBIEL|OFDOBIEL"],
            ["20260731|1|1"],
            ["P|||BDY;C;000000001;E;P;"],
            ["1|1|1"],
        )

        result = service.generate(self._request())

        self.assertIs(result.source, DataSourceChoice.ARCHIVE)
        self.assertEqual((result.input_code, result.output_code), ("IFDOBIEL", "OFDOBIEL"))
        self.assertEqual(runner.pending, 0)

    def test_discovery_collapses_upload_and_file_log_evidence_without_summing(self) -> None:
        candidates = _parse_candidates(
            [
                "UPLOAD_MASTER|ACTIVE|IFDOBIEL|2",
                "FILE_LOG|ACTIVE|IFDOBIEL|9",
            ]
        )

        self.assertEqual(len(candidates), 1)
        self.assertIs(candidates[0].source, DataSourceChoice.ACTIVE)
        self.assertEqual(candidates[0].input_code, "IFDOBIEL")
        self.assertEqual(candidates[0].record_count, 9)
        self.assertEqual(candidates[0].upload_record_count, 2)
        self.assertEqual(
            candidates[0].evidence_kinds,
            frozenset({"UPLOAD_MASTER", "FILE_LOG"}),
        )

    def test_file_log_without_upload_rows_never_creates_empty_output(self) -> None:
        service, runner = self._service(
            ["FILE_LOG|ARCHIVE|IFDOBIEL|2"],
            ["IFDOBIEL|OFDOBIEL"],
        )

        with self.assertRaisesRegex(
            OutputFileGenerationError,
            r"only in the file log.*upload rows.*empty client file",
        ):
            service.generate(self._request())

        self.assertEqual(len(runner.scripts), 2)
        self.assertEqual(runner.pending, 0)
        self.assertFalse((self.root / "output").exists())

    def test_no_process_evidence_names_all_gi_repositories(self) -> None:
        service, runner = self._service([])

        with self.assertRaises(OutputFileGenerationError) as raised:
            service.generate(self._request())

        message = str(raised.exception)
        self.assertRegex(
            message,
            r"GI repositories.*GITU_UPLOAD_MASTER.*GITA_FILE_LOG",
        )
        self.assertIn("may not exist or may have been purged", message)
        self.assertIn("cannot be reconstructed automatically", message)
        self.assertEqual(len(runner.scripts), 1)
        self.assertEqual(runner.pending, 0)

    def test_observed_unsupported_interface_reports_mapping_and_expected_qa_package(
        self,
    ) -> None:
        service, runner = self._service(
            ["UPLOAD_MASTER|ACTIVE|IFDDUPLD|1"],
            ["IFDDUPLD|OFDDUPLD"],
        )

        with self.assertRaises(OutputFileGenerationError) as raised:
            service.generate(self._request(process_ref_no="5328716"))

        message = str(raised.exception)
        self.assertIn("IFDDUPLD->OFDDUPLD", message)
        self.assertIn("QA package GIPKS_OFDDUPLD", message)
        self.assertIn("not implemented yet", message)
        self.assertNotIn("upload rows are unavailable", message)
        self.assertTrue(
            any("GITM_INTERFACE_DEFINITION" in script for script in runner.scripts)
        )
        self.assertEqual(len(runner.scripts), 2)
        self.assertEqual(runner.pending, 0)

    def test_detected_interface_without_outgoing_mapping_is_reported_separately(
        self,
    ) -> None:
        service, runner = self._service(
            ["UPLOAD_MASTER|ACTIVE|IFDDUPLD|1"],
            [],
        )

        with self.assertRaises(OutputFileGenerationError) as raised:
            service.generate(self._request())

        message = str(raised.exception)
        self.assertIn("IFDDUPLD", message)
        self.assertIn("no OUTGOING_INTERFACE configured", message)
        self.assertNotIn("GIPKS_", message)
        self.assertEqual(len(runner.scripts), 2)
        self.assertEqual(runner.pending, 0)

    def test_unsupported_interface_only_in_log_reports_missing_body_and_adapter(
        self,
    ) -> None:
        service, runner = self._service(
            ["FILE_LOG|ARCHIVE|IFDDUPLD|1"],
            ["IFDDUPLD|OFDDUPLD"],
        )

        with self.assertRaises(OutputFileGenerationError) as raised:
            service.generate(self._request(process_ref_no="5328716"))

        message = str(raised.exception)
        self.assertIn("IFDDUPLD->OFDDUPLD", message)
        self.assertIn("found only in GITA_FILE_LOG", message)
        self.assertIn("upload rows are unavailable", message)
        self.assertIn("no reconstructible body remains", message)
        self.assertIn("QA package GIPKS_OFDDUPLD", message)
        self.assertEqual(len(runner.scripts), 2)
        self.assertEqual(runner.pending, 0)

    def test_mixed_supported_and_unsupported_interfaces_never_generate_partial_output(
        self,
    ) -> None:
        service, runner = self._service(
            [
                "UPLOAD_MASTER|ACTIVE|ACCBLOCK|1",
                "FILE_LOG|ACTIVE|IFDDUPLD|1",
            ],
            ["ACCBLOCK|ACCBLKOU", "IFDDUPLD|OFDDUPLD"],
        )

        with self.assertRaisesRegex(
            OutputFileGenerationError,
            "IFDDUPLD->OFDDUPLD.*upload rows are unavailable.*GIPKS_OFDDUPLD",
        ):
            service.generate(self._request(process_ref_no="5328716"))

        self.assertEqual(len(runner.scripts), 2)
        self.assertFalse((self.root / "output").exists())
        self.assertEqual(runner.pending, 0)

    def test_accblock_rejects_unsupported_statuses_without_saving(self) -> None:
        service, runner = self._service(
            ["UPLOAD_MASTER|ACTIVE|ACCBLOCK|2"],
            ["ACCBLOCK|ACCBLKOU"],
            ["20260730|1|1"],
            ["142355"],
            [
                "P|BDY;000000001;100;CLP;BLOQUEO;Y;;;",
                "X|BDY;000000002;200;CLP;BLOQUEO;N;E001;Bloqueo;",
            ],
        )

        with self.assertRaisesRegex(
            OutputFileGenerationError,
            "ACCBLOCK contains unsupported statuses: X",
        ):
            service.generate(self._request())

        self.assertEqual(runner.pending, 0)
        self.assertFalse(
            (self.root / "output" / "Chile" / "ACCBLKOU_20260730.TXT").exists()
        )

    def test_sqlcl_exit_130_is_reported_as_cancellation(self) -> None:
        service, runner = self._service(RunResult(130, "", "Cancelled"))

        with self.assertRaisesRegex(GenerationCancelled, "cancelled"):
            service.generate(self._request())

        self.assertEqual(len(runner.scripts), 1)
        self.assertEqual(runner.pending, 0)

    def test_existing_file_is_not_overwritten_without_explicit_permission(self) -> None:
        output_path = self.root / "output" / "Chile" / "OFDOBIEL_20260731.TXT"
        output_path.parent.mkdir(parents=True)
        output_path.write_bytes(b"existing-client-file\n")
        service, runner = self._service(
            ["UPLOAD_MASTER|ARCHIVE|IFDOBIEL|1"],
            ["IFDOBIEL|OFDOBIEL"],
            ["20260731|1|1"],
            ["P|||BDY;C;000000001;E;P;"],
            ["1|1|1"],
        )

        with self.assertRaisesRegex(OutputFileGenerationError, "already exists"):
            service.generate(self._request(overwrite=False))

        self.assertEqual(output_path.read_bytes(), b"existing-client-file\n")
        self.assertEqual(list(output_path.parent.glob(".*.tmp")), [])
        self.assertEqual(runner.pending, 0)

    def test_explicit_overwrite_replaces_existing_file_atomically(self) -> None:
        output_path = self.root / "output" / "Chile" / "OFDOBIEL_20260731.TXT"
        output_path.parent.mkdir(parents=True)
        output_path.write_bytes(b"old-file\n")
        service, runner = self._service(
            ["UPLOAD_MASTER|ARCHIVE|IFDOBIEL|1"],
            ["IFDOBIEL|OFDOBIEL"],
            ["20260731|1|1"],
            ["P|||BDY;C;000000001;E;P;"],
            ["1|1|1"],
        )

        result = service.generate(self._request(overwrite=True))

        self.assertEqual(result.output_path, output_path.resolve())
        self.assertNotEqual(output_path.read_bytes(), b"old-file\n")
        self.assertEqual(list(output_path.parent.glob(".*.tmp")), [])
        self.assertEqual(runner.pending, 0)

    def test_cancellation_after_last_query_prevents_file_write(self) -> None:
        runner = _CancellingOnLastRunner(
            [
                ["UPLOAD_MASTER|ARCHIVE|IFDOBIEL|1"],
                ["IFDOBIEL|OFDOBIEL"],
                ["20260731|1|1"],
                ["P|||BDY;C;000000001;E;P;"],
            ]
        )
        service = OutputFileGenerationService(
            self.config,
            runner_factory=lambda _path: runner,
            decryptor=lambda _encrypted: "fake-password",
            output_root=self.root / "output",
        )
        cancel_event = threading.Event()

        with self.assertRaisesRegex(GenerationCancelled, "cancelled"):
            service.generate(self._request(), cancel_event=cancel_event)

        self.assertFalse((self.root / "output").exists())
        self.assertEqual(runner.pending, 0)

    def test_ofdobiel_can_generate_an_empty_contract_file(self) -> None:
        service, runner = self._service(
            ["UPLOAD_MASTER|ARCHIVE|IFDOBIEL|1"],
            ["IFDOBIEL|OFDOBIEL"],
            ["20260731|1|1"],
            [],
            ["1|1|1"],
        )

        result = service.generate(self._request())

        self.assertEqual(
            result.lines,
            ("HDR;OFDOBIEL.txt;20260731;", "TLR;0;"),
        )
        self.assertEqual(result.body_count, 0)
        self.assertEqual(result.status_counts, {})
        self.assertEqual(runner.pending, 0)

    def test_country_path_traversal_is_rejected_before_sqlcl(self) -> None:
        service, runner = self._service()
        target = OracleTarget(
            country="..\\..\\outside",
            database_key="prod-db",
            credential_key="shared-prod",
            tns="FXBFCL_19C_PROD_OCI",
        )
        request = GenerationRequest(target=target, process_ref_no="1234567")

        with self.assertRaisesRegex(OutputFileGenerationError, "country is not supported"):
            service.generate(request)

        self.assertEqual(len(runner.scripts), 0)

    def test_sqlcl_error_is_actionable_and_redacts_connection(self) -> None:
        service, runner = self._service(
            RunResult(
                1,
                "",
                (
                    "ORA-01017: invalid login for "
                    "fake_user/fake-password@FXBFCL_19C_PROD_OCI\n"
                ),
            )
        )

        with self.assertRaises(OutputFileGenerationError) as raised:
            service.generate(self._request())

        message = str(raised.exception)
        self.assertIn("ORA-01017", message)
        self.assertIn("[connection redacted]", message)
        self.assertNotIn("fake-password", message)
        self.assertEqual(runner.pending, 0)

    def test_sqlcl_timeout_never_exposes_partial_client_rows(self) -> None:
        secret_row = "BDY;PRIVATE-CUSTOMER-DATA;SHOULD-NOT-BE-LOGGED;"
        service, runner = self._service(
            RunResult(124, secret_row + "\n", "Timed out after 120s")
        )

        with self.assertRaises(OutputFileGenerationError) as raised:
            service.generate(self._request())

        message = str(raised.exception)
        self.assertIn("Timed out after 120s", message)
        self.assertIn("DISCOVERY", message)
        self.assertNotIn(secret_row, message)
        self.assertNotIn("PRIVATE-CUSTOMER-DATA", message)
        self.assertEqual(runner.pending, 0)

    def test_nonzero_stdout_is_never_used_as_an_error_message(self) -> None:
        self.config.credentials["chile"]["PROD-DB-DR"] = {
            "SHARED-PROD": {
                **self.config.credential,
                "tns": "FXBFCL_19C_PROD_OCI_DR",
            }
        }
        leaked_rows = (
            "BDY;ACCOUNT123;SQL Error;SECRET;",
            "BDY;ACCOUNT123;ORA-20000: error for SECRET;",
            "BDY;ACCOUNT123;Closed Connection;SECRET;",
        )
        for leaked_row in leaked_rows:
            with self.subTest(leaked_row=leaked_row):
                service, runner = self._service(
                    RunResult(1, leaked_row, ""),
                    ["UPLOAD_MASTER|ARCHIVE|IFDOBIEL|1"],
                )

                with self.assertRaises(OutputFileGenerationError) as raised:
                    service.generate(self._request())

                self.assertEqual(str(raised.exception), "SQLcl failed with exit code 1")
                self.assertNotIn("ACCOUNT123", str(raised.exception))
                self.assertNotIn("SECRET", str(raised.exception))
                self.assertEqual(
                    runner.connections,
                    ["fake_user/fake-password@FXBFCL_19C_PROD_OCI"],
                )
                self.assertEqual(runner.pending, 1)

    def test_programmatic_target_must_still_be_a_configured_prod_login(self) -> None:
        service, runner = self._service()
        forged = OracleTarget(
            country="chile",
            database_key="prod-db",
            credential_key="shared-prod",
            tns="CHILE_QA_19C",
        )
        request = GenerationRequest(target=forged, process_ref_no="1234567")

        with self.assertRaisesRegex(OutputFileGenerationError, "current PROD target"):
            service.generate(request)

        self.assertEqual(len(runner.scripts), 0)

    def test_known_qa_alias_is_rejected_even_if_saved_in_prod_bucket(self) -> None:
        self.config.credential["tns"] = "CHILE_QA_19C"
        service, runner = self._service()
        mislabeled = OracleTarget(
            country="chile",
            database_key="prod-db",
            credential_key="shared-prod",
            tns="CHILE_QA_19C",
        )

        self.assertEqual(service.targets("chile"), [])
        with self.assertRaisesRegex(OutputFileGenerationError, "current PROD target"):
            service.generate(
                GenerationRequest(target=mislabeled, process_ref_no="1234567")
            )

        self.assertEqual(len(runner.scripts), 0)

    def test_ofdobiel_rejects_unsupported_status_without_saving(self) -> None:
        service, runner = self._service(
            ["UPLOAD_MASTER|ARCHIVE|IFDOBIEL|1"],
            ["IFDOBIEL|OFDOBIEL"],
            ["20260731|1|1"],
            ["<NULL>|||BDY;C;000000001;E;;"],
        )

        with self.assertRaisesRegex(
            OutputFileGenerationError,
            "IFDOBIEL contains unsupported statuses: <NULL>",
        ):
            service.generate(self._request())

        self.assertEqual(runner.pending, 0)
        self.assertFalse(
            (self.root / "output" / "Chile" / "OFDOBIEL_20260731.TXT").exists()
        )

    def test_ambiguous_upload_dates_abort_automatic_generation(self) -> None:
        service, runner = self._service(
            ["UPLOAD_MASTER|ARCHIVE|IFDOBIEL|1"],
            ["IFDOBIEL|OFDOBIEL"],
            ["20260731|2|2"],
        )

        with self.assertRaisesRegex(
            OutputFileGenerationError,
            "more than one upload date",
        ):
            service.generate(self._request())

        self.assertEqual(runner.pending, 0)
        self.assertFalse((self.root / "output").exists())

    def test_malformed_framing_never_logs_returned_client_rows(self) -> None:
        secret_row = "BDY;PRIVATE-CUSTOMER-DATA;SHOULD-NOT-BE-LOGGED;"
        service, runner = self._service(RunResult(0, secret_row, ""))

        with self.assertLogs(
            "features.output_file_generation.service",
            level="WARNING",
        ) as captured, self.assertRaisesRegex(
            OutputFileGenerationError,
            "unexpected response",
        ):
            service.generate(self._request())

        log_output = "\n".join(captured.output)
        self.assertIn("begin_markers=0", log_output)
        self.assertNotIn(secret_row, log_output)
        self.assertNotIn("PRIVATE-CUSTOMER-DATA", log_output)
        self.assertEqual(runner.pending, 0)


if __name__ == "__main__":
    unittest.main()
