--Accept ACC_NO PROMPT 'Enter the Account Number : '
--209991341468
SET VERIFY OFF
SET HEAD OFF
SET ARRAY 1
SET LINESIZE 32767
SET PAGESIZE 50000
SET LONG 1000000
SET ECHO OFF
SET TRIMSPOOL ON
SET NUMFORMAT 9999999999999999.99
set ddl segment_attributes off
set ddl storage off
set ddl tablespace off
set feedback off
variable CUSTOMER_NO varchar2(30);
variable process_no number;
variable id number;
variable UTIL_ID varchar2(35);
variable BRN varchar2(35);
variable ALT_ACC_NO varchar2(35);

--spool "C:\Users\Diego Pavez\Desktop\sqlcl\spools\spools_files\CL_Acc_Spool_&1..SQL"
spool "C:\Users\Diego Pavez\Desktop\sqlcl\spools\spools_files\Accounts\Chile\CL_Acc_Spool_&1..SQL"

SET FEEDBACK OFF

begin 
SELECT a.BRANCH_CODE, a.customer_id,a.process_no , l.id, a.ALT_ACC_NO into :BRN,:customer_no,:process_no ,:id , :ALT_ACC_NO FROM   cltb_account_master a, getm_liab l where a.account_number = '&1' and a.CUSTOMER_ID = l.liab_no; 
end;
/
begin 
select UTIL_ID into :UTIL_ID from GETB_UTILS WHERE LIAB_ID = :id;
exception when others then :UTIL_ID := '';
end;
/
set feedback off
set sqlformat DEFAULT
select 'ALTER SESSION SET NLS_DATE_LANGUAGE ='||chr(39)||value||chr(39)||';' from nls_session_parameters where parameter = 'NLS_DATE_LANGUAGE';
SELECT 'DELETE CLTB_ACCOUNT_ADVICE_SUPPRESS WHERE ACCOUNT_NUMBER = ''&1'' AND BRANCH_CODE = '''||:BRN||''';' FROM DUAL;  
SELECT 'DELETE FROM CLTB_ACCOUNT_APPS_MASTER WHERE ALT_ACC_NO = (SELECT ALT_ACC_NO FROM CLTBS_ACCOUNT_APPS_MASTER WHERE ACCOUNT_NUMBER = ''&1'' AND BRANCH_CODE = '''||:BRN||''');' FROM DUAL;
SELECT 'DELETE CLTB_ACCOUNT_PROPERTY_HIST WHERE ACCOUNT_NUMBER = ''&1'' AND BRANCH_CODE = '''||:BRN||''';' FROM DUAL;
SELECT 'DELETE CLTB_ACCOUNT_CREDIT_SCORE WHERE ACCOUNT_NUMBER = ''&1'' AND BRANCH_CODE = '''||:BRN||''';' FROM DUAL;
SELECT 'DELETE CLTB_ASSET_VEHICLE_HISTORY WHERE ACCOUNT_NUMBER = ''&1'' AND BRANCH_CODE = '''||:BRN||''';' FROM DUAL;
SELECT 'DELETE CLTB_ASSET_HOME_HISTORY WHERE ACCOUNT_NUMBER = ''&1'' AND BRANCH_CODE = '''||:BRN||''';' FROM DUAL;
SELECT 'DELETE CLTB_ASSET_OTHERS_HISTORY WHERE ACCOUNT_NUMBER = ''&1'' AND BRANCH_CODE = '''||:BRN||''';' FROM DUAL;
SELECT 'DELETE CLTB_LIQ_C WHERE ACCOUNT_NUMBER = ''&1'' AND BRANCH_CODE = '''||:BRN||''';' FROM DUAL;
SELECT 'DELETE CLTB_LIQ_SETTLEMENTS_C WHERE ACCOUNT_NUMBER = ''&1'' AND BRANCH_CODE = '''||:BRN||''';' FROM DUAL;
SELECT 'DELETE CLTP_ACCOUNT_MASTER WHERE ACCOUNT_NUMBER = ''&1'' AND BRANCH_CODE = '''||:BRN||''';' FROM DUAL;
SELECT 'DELETE CLTB_ACCOUNT_CHANGE_LOG WHERE ACCOUNT_NUMBER = ''&1'' AND BRANCH_CODE = '''||:BRN||''';' FROM DUAL;
SELECT 'DELETE CLTB_ACCOUNT_COMPONENTS WHERE ACCOUNT_NUMBER = ''&1'' AND BRANCH_CODE = '''||:BRN||''';' FROM DUAL;
SELECT 'DELETE CLTB_ACCOUNT_COMPONENTS_AMND WHERE ACCOUNT_NUMBER = ''&1'' AND BRANCH_CODE = '''||:BRN||''';' FROM DUAL;
SELECT 'DELETE CLTB_ACCOUNT_COMP_BALANCES WHERE ACCOUNT_NUMBER = ''&1'' AND BRANCH_CODE = '''||:BRN||''';' FROM DUAL;
SELECT 'DELETE CLTB_ACCOUNT_COMP_BAL_BREAKUP WHERE ACCOUNT_NUMBER = ''&1'' AND BRANCH_CODE = '''||:BRN||''';' FROM DUAL;
SELECT 'DELETE CLTB_ACCOUNT_COMP_BAL_CRAC WHERE ACCOUNT_NUMBER = ''&1'' AND BRANCH_CODE = '''||:BRN||''';' FROM DUAL;
SELECT 'DELETE CLTB_ACCOUNT_COMP_BAL_SUMMARY WHERE ACCOUNT_NUMBER = ''&1'' AND BRANCH_CODE = '''||:BRN||''';' FROM DUAL;
SELECT 'DELETE CLTB_ACCOUNT_COMP_CALC WHERE ACCOUNT_NUMBER = ''&1'' AND BRANCH_CODE = '''||:BRN||''';' FROM DUAL;
SELECT 'DELETE CLTB_ACCOUNT_COMP_HISTORY WHERE ACCOUNT_NUMBER = ''&1'' AND BRANCH_CODE = '''||:BRN||''';' FROM DUAL;
SELECT 'DELETE CLTB_ACCOUNT_COMP_SCH WHERE ACCOUNT_NUMBER = ''&1'' AND BRANCH_CODE = '''||:BRN||''';' FROM DUAL;
SELECT 'DELETE CLTB_ACCOUNT_COMP_SCH_AMND WHERE ACCOUNT_NUMBER = ''&1'' AND BRANCH_CODE = '''||:BRN||''';' FROM DUAL;
SELECT 'DELETE CLTB_ACCOUNT_COMP_SCH_CRAC WHERE ACCOUNT_NUMBER = ''&1'' AND BRANCH_CODE = '''||:BRN||''';' FROM DUAL;
SELECT 'DELETE CLTB_ACCOUNT_COMP_SCH_HISTORY WHERE ACCOUNT_NUMBER = ''&1'' AND BRANCH_CODE = '''||:BRN||''';' FROM DUAL;
SELECT 'DELETE CLTB_ACCOUNT_DSBR_CHARGES WHERE ACCOUNT_NUMBER = ''&1'' AND BRANCH_CODE = '''||:BRN||''';' FROM DUAL;
SELECT 'DELETE CLTB_ACCOUNT_DSBR_DETAIL WHERE ACCOUNT_NUMBER = ''&1'' AND BRANCH_CODE = '''||:BRN||''';' FROM DUAL;
SELECT 'DELETE CLTB_ACCOUNT_DSBR_DETAIL_HIST WHERE ACCOUNT_NUMBER = ''&1'' AND BRANCH_CODE = '''||:BRN||''';' FROM DUAL;
SELECT 'DELETE CLTB_ACCOUNT_DSBR_MASTER WHERE ACCOUNT_NUMBER = ''&1'' AND BRANCH_CODE = '''||:BRN||''';' FROM DUAL;
SELECT 'DELETE CLTB_ACCOUNT_DSBR_MASTER_HIST WHERE ACCOUNT_NUMBER = ''&1'' AND BRANCH_CODE = '''||:BRN||''';' FROM DUAL;
SELECT 'DELETE CLTP_ACCOUNT_COMP_BAL_BREAKUP WHERE ACCOUNT_NUMBER = ''&1'' AND BRANCH_CODE = '''||:BRN||''';' FROM DUAL;
SELECT 'DELETE CLTB_ACCOUNT_EVENTS_ADVICES WHERE ACCOUNT_NUMBER = ''&1'' AND BRANCH_CODE = '''||:BRN||''';' FROM DUAL;
SELECT 'DELETE CLTP_ACCOUNT_COMP_CALC WHERE ACCOUNT_NUMBER = ''&1'' AND BRANCH_CODE = '''||:BRN||''';' FROM DUAL;
SELECT 'DELETE CLTB_ACCOUNT_EVENTS_DIARY WHERE ACCOUNT_NUMBER = ''&1'' AND BRANCH_CODE = '''||:BRN||''';' FROM DUAL;
SELECT 'DELETE CLTB_ACCOUNT_EVENTS_PROCESSED WHERE ACCOUNT_NUMBER = ''&1'' AND BRANCH_CODE = '''||:BRN||''';' FROM DUAL;
SELECT 'DELETE CLTB_ACCOUNT_EVENT_USERDEF WHERE ACCOUNT_NUMBER = ''&1'' AND BRANCH_CODE = '''||:BRN||''';' FROM DUAL;
SELECT 'DELETE CLTB_ACCOUNT_HISTORY WHERE ACCOUNT_NUMBER = ''&1'' AND BRANCH_CODE = '''||:BRN||''';' FROM DUAL;
SELECT 'DELETE CLTB_ACCOUNT_HOL_PERDS WHERE ACCOUNT_NUMBER = ''&1'' AND BRANCH_CODE = '''||:BRN||''';' FROM DUAL;
SELECT 'DELETE CLTB_ACCOUNT_HOL_PERDS_AMND WHERE ACCOUNT_NUMBER = ''&1'' AND BRANCH_CODE = '''||:BRN||''';' FROM DUAL;
SELECT 'ALTER TABLE CLTB_ACCOUNT_LINKAGES DISABLE ALL TRIGGERS;' FROM DUAL;
SELECT 'DELETE CLTB_ACCOUNT_LINKAGES WHERE ACCOUNT_NUMBER = ''&1'' AND BRANCH_CODE = '''||:BRN||''';' FROM DUAL;
SELECT 'ALTER TABLE CLTB_ACCOUNT_LINKAGES ENABLE ALL TRIGGERS;' FROM DUAL;
SELECT 'DELETE CLTB_ACCOUNT_LINKAGES_AMND WHERE ACCOUNT_NUMBER = ''&1'' AND BRANCH_CODE = '''||:BRN||''';' FROM DUAL;
SELECT 'DELETE CLTB_ACCOUNT_LINKAGES_HISTORY WHERE ACCOUNT_NUMBER = ''&1'' AND BRANCH_CODE = '''||:BRN||''';' FROM DUAL;
SELECT 'DELETE CLTB_ACCOUNT_MASTER_AMND WHERE ACCOUNT_NUMBER = ''&1'' AND BRANCH_CODE = '''||:BRN||''';' FROM DUAL;
SELECT 'DELETE CLTB_ACCOUNT_MASTER_AMND_HIST WHERE ACCOUNT_NUMBER = ''&1'' AND BRANCH_CODE = '''||:BRN||''';' FROM DUAL;
SELECT 'DELETE CLTB_ACCOUNT_PARTIES WHERE ACCOUNT_NUMBER = ''&1'' AND BRANCH_CODE = '''||:BRN||''';' FROM DUAL;
SELECT 'DELETE CLTB_ACCOUNT_PARTIES_AMND WHERE ACCOUNT_NUMBER = ''&1'' AND BRANCH_CODE = '''||:BRN||''';' FROM DUAL;
SELECT 'DELETE CLTB_ACCOUNT_PARTIES_HISTORY WHERE ACCOUNT_NUMBER = ''&1'' AND BRANCH_CODE = '''||:BRN||''';' FROM DUAL;
SELECT 'DELETE CLTB_ACCOUNT_PROMOTIONS WHERE ACCOUNT_NUMBER = ''&1'' AND BRANCH_CODE = '''||:BRN||''';' FROM DUAL;
SELECT 'DELETE CLTB_ACCOUNT_PROMOTIONS_HIST WHERE ACCOUNT_NUMBER = ''&1'' AND BRANCH_CODE = '''||:BRN||''';' FROM DUAL;
SELECT 'DELETE CLTB_ACCOUNT_ROLL WHERE ACCOUNT_NUMBER = ''&1'' AND BRANCH_CODE = '''||:BRN||''';' FROM DUAL;
SELECT 'DELETE CLTB_ACCOUNT_ROLL_COMP WHERE ACCOUNT_NUMBER = ''&1'' AND BRANCH_CODE = '''||:BRN||''';' FROM DUAL;
SELECT 'DELETE CLTB_ACCOUNT_ROLL_COMP_AMND WHERE ACCOUNT_NUMBER = ''&1'' AND BRANCH_CODE = '''||:BRN||''';' FROM DUAL;
SELECT 'DELETE CLTB_ACCOUNT_SCHEDULES WHERE ACCOUNT_NUMBER = ''&1'' AND BRANCH_CODE = '''||:BRN||''';' FROM DUAL;
SELECT 'DELETE CLTB_ACCOUNT_SCHEDULES_AMND WHERE ACCOUNT_NUMBER = ''&1'' AND BRANCH_CODE = '''||:BRN||''';' FROM DUAL;
SELECT 'DELETE CLTB_ACCOUNT_SCHEDULES_BAL WHERE ACCOUNT_NUMBER = ''&1'' AND BRANCH_CODE = '''||:BRN||''';' FROM DUAL;
SELECT 'DELETE CLTB_ACCOUNT_SCHEDULES_CRAC WHERE ACCOUNT_NUMBER = ''&1'' AND BRANCH_CODE = '''||:BRN||''';' FROM DUAL;
SELECT 'DELETE CLTB_ACCOUNT_SCHEDULES_HISTORY WHERE ACCOUNT_NUMBER = ''&1'' AND BRANCH_CODE = '''||:BRN||''';' FROM DUAL;
SELECT 'DELETE CLTB_ACCOUNT_SCH_BAL_CRAC WHERE ACCOUNT_NUMBER = ''&1'' AND BRANCH_CODE = '''||:BRN||''';' FROM DUAL;
SELECT 'DELETE CLTB_ACCOUNT_STCH_CHARGES WHERE ACCOUNT_NUMBER = ''&1'' AND BRANCH_CODE = '''||:BRN||''';' FROM DUAL;
SELECT 'DELETE CLTB_ACCOUNT_STSH_CHARGES WHERE ACCOUNT_NUMBER = ''&1'' AND BRANCH_CODE = '''||:BRN||''';' FROM DUAL;
SELECT 'DELETE CLTB_ACCOUNT_UDE_EFF_DATES WHERE ACCOUNT_NUMBER = ''&1'' AND BRANCH_CODE = '''||:BRN||''';' FROM DUAL;
SELECT 'DELETE CLTB_ACCOUNT_UDE_VALUES WHERE ACCOUNT_NUMBER = ''&1'' AND BRANCH_CODE = '''||:BRN||''';' FROM DUAL;
SELECT 'DELETE CLTB_ACCOUNT_UDE_VALUES_AMND WHERE ACCOUNT_NUMBER = ''&1'' AND BRANCH_CODE = '''||:BRN||''';' FROM DUAL;
SELECT 'DELETE CLTB_ACCOUNT_VAMD WHERE ACCOUNT_NUMBER = ''&1'' AND BRANCH_CODE = '''||:BRN||''';' FROM DUAL;
SELECT 'DELETE CLTB_ACCOUNT_VAMD_HIST WHERE ACCOUNT_NUMBER = ''&1'' AND BRANCH_CODE = '''||:BRN||''';' FROM DUAL;
SELECT 'DELETE CLTB_ACC_COMPONENTS_AMND_HIST WHERE ACCOUNT_NUMBER = ''&1'' AND BRANCH_CODE = '''||:BRN||''';' FROM DUAL;
SELECT 'DELETE CLTB_ACC_COMP_BALANCES_TEMP WHERE ACCOUNT_NUMBER = ''&1'' AND BRANCH_CODE = '''||:BRN||''';' FROM DUAL;
SELECT 'DELETE CLTB_ACC_COMP_SCH_AMND_HIST WHERE ACCOUNT_NUMBER = ''&1'' AND BRANCH_CODE = '''||:BRN||''';' FROM DUAL;
SELECT 'DELETE CLTB_ACC_DSBR_CHARGES_HIST WHERE ACCOUNT_NUMBER = ''&1'' AND BRANCH_CODE = '''||:BRN||''';' FROM DUAL;
SELECT 'DELETE CLTB_ACC_HOL_PERDS_AMND_HIST WHERE ACCOUNT_NUMBER = ''&1'' AND BRANCH_CODE = '''||:BRN||''';' FROM DUAL;
SELECT 'DELETE CLTB_ACC_HOL_PERDS_HISTORY WHERE ACCOUNT_NUMBER = ''&1'' AND BRANCH_CODE = '''||:BRN||''';' FROM DUAL;
SELECT 'DELETE CLTB_ACC_LINKAGES_AMND_HIST WHERE ACCOUNT_NUMBER = ''&1'' AND BRANCH_CODE = '''||:BRN||''';' FROM DUAL;
SELECT 'DELETE CLTB_ACC_PARTIES_AMND_HIST WHERE ACCOUNT_NUMBER = ''&1'' AND BRANCH_CODE = '''||:BRN||''';' FROM DUAL;
SELECT 'DELETE CLTB_ACC_PROMOTIONS_AMND WHERE ACCOUNT_NUMBER = ''&1'' AND BRANCH_CODE = '''||:BRN||''';' FROM DUAL;
SELECT 'DELETE CLTB_ACC_PROMOTIONS_AMND_HIST WHERE ACCOUNT_NUMBER = ''&1'' AND BRANCH_CODE = '''||:BRN||''';' FROM DUAL;
SELECT 'DELETE CLTB_ACC_ROLL_COMP_AMND_HIST WHERE ACCOUNT_NUMBER = ''&1'' AND BRANCH_CODE = '''||:BRN||''';' FROM DUAL;
SELECT 'DELETE CLTB_ACC_SCHEDULES_AMND_HIST WHERE ACCOUNT_NUMBER = ''&1'' AND BRANCH_CODE = '''||:BRN||''';' FROM DUAL;
SELECT 'DELETE CLTB_ACC_UDE_EFFDT_AMND_HIST WHERE ACCOUNT_NUMBER = ''&1'' AND BRANCH_CODE = '''||:BRN||''';' FROM DUAL;
SELECT 'DELETE CLTB_ACC_UDE_EFF_DATES_AMND WHERE ACCOUNT_NUMBER = ''&1'' AND BRANCH_CODE = '''||:BRN||''';' FROM DUAL;
SELECT 'DELETE CLTB_ACC_UDE_EFF_DATES_HISTORY WHERE ACCOUNT_NUMBER = ''&1'' AND BRANCH_CODE = '''||:BRN||''';' FROM DUAL;
SELECT 'DELETE CLTB_ACC_UDE_VALUES_AMND_HIST WHERE ACCOUNT_NUMBER = ''&1'' AND BRANCH_CODE = '''||:BRN||''';' FROM DUAL;
SELECT 'DELETE CLTB_ACC_UDE_VALUES_HISTORY WHERE ACCOUNT_NUMBER = ''&1'' AND BRANCH_CODE = '''||:BRN||''';' FROM DUAL;
SELECT 'DELETE CLTB_ADHOC_CHARGES WHERE ACCOUNT_NUMBER = ''&1'' AND BRANCH_CODE = '''||:BRN||''';' FROM DUAL;
SELECT 'DELETE CLTB_AMOUNT_PAID WHERE ACCOUNT_NUMBER = ''&1'' AND BRANCH_CODE = '''||:BRN||''';' FROM DUAL;
SELECT 'DELETE CLTB_AMOUNT_PAID_HISTORY WHERE ACCOUNT_NUMBER = ''&1'' AND BRANCH_CODE = '''||:BRN||''';' FROM DUAL;
SELECT 'DELETE CLTB_AMOUNT_RECD WHERE ACCOUNT_NUMBER = ''&1'' AND BRANCH_CODE = '''||:BRN||''';' FROM DUAL;
SELECT 'DELETE CLTB_AMOUNT_RECD_HISTORY WHERE ACCOUNT_NUMBER = ''&1'' AND BRANCH_CODE = '''||:BRN||''';' FROM DUAL;
SELECT 'DELETE CLTB_BCH_TAX WHERE ACCOUNT_NUMBER = ''&1'' AND BRANCH_CODE = '''||:BRN||''';' FROM DUAL;
SELECT 'DELETE CLTB_BCH_TAX_HISTORY WHERE ACCOUNT_NUMBER = ''&1'' AND BRANCH_CODE = '''||:BRN||''';' FROM DUAL;
SELECT 'DELETE CLTB_BCH_TAX_REVERSED WHERE ACCOUNT_NUMBER = ''&1'' AND BRANCH_CODE = '''||:BRN||''';' FROM DUAL;
SELECT 'DELETE CLTB_CALC_DATES WHERE ACCOUNT_NUMBER = ''&1'' AND BRANCH_CODE = '''||:BRN||''';' FROM DUAL;
SELECT 'DELETE CLTB_COMP_BALANCES_HISTORY WHERE ACCOUNT_NUMBER = ''&1'' AND BRANCH_CODE = '''||:BRN||''';' FROM DUAL;
SELECT 'DELETE CLTB_DISBR_SCHEDULES WHERE ACCOUNT_NUMBER = ''&1'' AND BRANCH_CODE = '''||:BRN||''';' FROM DUAL;
SELECT 'DELETE CLTB_DISBR_SCHEDULES_AMND WHERE ACCOUNT_NUMBER = ''&1'' AND BRANCH_CODE = '''||:BRN||''';' FROM DUAL;
SELECT 'DELETE CLTB_DISBR_SCH_AMND_HIST WHERE ACCOUNT_NUMBER = ''&1'' AND BRANCH_CODE = '''||:BRN||''';' FROM DUAL;
SELECT 'DELETE CLTB_EVENT_ENTRIES WHERE ACCOUNT_NUMBER = ''&1'' AND BRANCH_CODE = '''||:BRN||''';' FROM DUAL;
SELECT 'DELETE CLTB_EVENT_ENTRIES_PENDING WHERE ACCOUNT_NUMBER = ''&1'' AND BRANCH_CODE = '''||:BRN||''';' FROM DUAL;
SELECT 'DELETE CLTB_EVENT_OVD WHERE ACCOUNT_NUMBER = ''&1'' AND BRANCH_CODE = '''||:BRN||''';' FROM DUAL;
SELECT 'DELETE CLTB_EVENT_REMARKS WHERE ACCOUNT_NUMBER = ''&1'' AND BRANCH_CODE = '''||:BRN||''';' FROM DUAL;
SELECT 'DELETE CLTB_EXCEPTION_LOG WHERE ACCOUNT_NUMBER = ''&1'' AND BRANCH_CODE = '''||:BRN||''';' FROM DUAL;
SELECT 'DELETE CLTB_IFACEQRY_ONLINE_CALC WHERE ACCOUNT_NUMBER = ''&1'' AND BRANCH_CODE = '''||:BRN||''';' FROM DUAL;
SELECT 'DELETE CLTB_INACTIVE_EVENTS_DIARY WHERE ACCOUNT_NUMBER = ''&1'' AND BRANCH_CODE = '''||:BRN||''';' FROM DUAL;
SELECT 'DELETE CLTB_LIQ WHERE ACCOUNT_NUMBER = ''&1'' AND BRANCH_CODE = '''||:BRN||''';' FROM DUAL;
SELECT 'DELETE CLTB_LIQ_COMP_SETTLED WHERE ACCOUNT_NUMBER = ''&1'' AND BRANCH_CODE = '''||:BRN||''';' FROM DUAL;
SELECT 'DELETE CLTB_LIQ_COMP_SUMMARY WHERE ACCOUNT_NUMBER = ''&1'' AND BRANCH_CODE = '''||:BRN||''';' FROM DUAL;
SELECT 'DELETE CLTB_LIQ_PENAL_RATES WHERE ACCOUNT_NUMBER = ''&1'' AND BRANCH_CODE = '''||:BRN||''';' FROM DUAL;
SELECT 'DELETE CLTB_LIQ_SETTLEMENTS WHERE ACCOUNT_NUMBER = ''&1'' AND BRANCH_CODE = '''||:BRN||''';' FROM DUAL;
SELECT 'DELETE CLTB_LIQ_SUSPENSION WHERE ACCOUNT_NUMBER = ''&1'' AND BRANCH_CODE = '''||:BRN||''';' FROM DUAL;
SELECT 'DELETE CLTB_MANUAL_STCH WHERE ACCOUNT_NUMBER = ''&1'' AND BRANCH_CODE = '''||:BRN||''';' FROM DUAL;
SELECT 'DELETE CLTB_MANUAL_STSH WHERE ACCOUNT_NUMBER = ''&1'' AND BRANCH_CODE = '''||:BRN||''';' FROM DUAL;
SELECT 'DELETE CLTB_MIG_REFERNCE WHERE ACCOUNT_NUMBER = ''&1'' AND BRANCH_CODE = '''||:BRN||''';' FROM DUAL;
SELECT 'DELETE CLTB_PROCESSED_REVISIONS WHERE ACCOUNT_NUMBER = ''&1'' AND BRANCH_CODE = '''||:BRN||''';' FROM DUAL;
SELECT 'DELETE CLTB_PROV_HANDOFF WHERE ACCOUNT_NUMBER = ''&1'' AND BRANCH_CODE = '''||:BRN||''';' FROM DUAL;
SELECT 'DELETE CLTB_RECON WHERE ACCOUNT_NUMBER = ''&1'' AND BRANCH_CODE = '''||:BRN||''';' FROM DUAL;
SELECT 'DELETE CLTB_REVISION_ACCOUNTS WHERE ACCOUNT_NUMBER = ''&1'' AND BRANCH_CODE = '''||:BRN||''';' FROM DUAL;
SELECT 'DELETE CLTB_REVN_SCHEDULES WHERE ACCOUNT_NUMBER = ''&1'' AND BRANCH_CODE = '''||:BRN||''';' FROM DUAL;
SELECT 'DELETE CLTB_REVN_SCHEDULES_AMND WHERE ACCOUNT_NUMBER = ''&1'' AND BRANCH_CODE = '''||:BRN||''';' FROM DUAL;
SELECT 'DELETE CLTB_REVN_SCH_AMND_HIST WHERE ACCOUNT_NUMBER = ''&1'' AND BRANCH_CODE = '''||:BRN||''';' FROM DUAL;
SELECT 'DELETE CLTB_ROLL_COMPONENTS WHERE ACCOUNT_NUMBER = ''&1'' AND BRANCH_CODE = '''||:BRN||''';' FROM DUAL;
SELECT 'DELETE CLTB_ROLL_COMP_SETTLED WHERE ACCOUNT_NUMBER = ''&1'' AND BRANCH_CODE = '''||:BRN||''';' FROM DUAL;
SELECT 'DELETE CLTB_ROLL_SETTLEMENTS WHERE ACCOUNT_NUMBER = ''&1'' AND BRANCH_CODE = '''||:BRN||''';' FROM DUAL;
SELECT 'DELETE FROM CLTB_SDE_VALUES WHERE ACCOUNT_NUMBER = ''&1''AND BRANCH_CODE = '''||:BRN||''';' FROM DUAL;
SELECT 'DELETE CLTP_ACCOUNT_COMP_BALANCES WHERE ACCOUNT_NUMBER = ''&1'' AND BRANCH_CODE = '''||:BRN||''';' FROM DUAL;
SELECT 'DELETE CLTP_ACCOUNT_COMP_SCH WHERE ACCOUNT_NUMBER = ''&1'' AND BRANCH_CODE = '''||:BRN||''' ;' FROM DUAL;
SELECT 'DELETE CLTP_ACCOUNT_SCHEDULES WHERE ACCOUNT_NUMBER = ''&1'' AND BRANCH_CODE = '''||:BRN||''';' FROM DUAL;
SELECT 'DELETE CLTP_LIQ WHERE ACCOUNT_NUMBER = ''&1'' AND BRANCH_CODE = '''||:BRN||''';' FROM DUAL;
SELECT 'DELETE CLTS_LIQ WHERE ACCOUNT_NUMBER = ''&1'' AND BRANCH_CODE = '''||:BRN||''';' FROM DUAL;
SELECT 'DELETE CLTS_LIQ_COMP_SETTLED WHERE ACCOUNT_NUMBER = ''&1'' AND BRANCH_CODE = '''||:BRN||''';' FROM DUAL;
SELECT 'DELETE CLTS_LIQ_COMP_SUMMARY WHERE ACCOUNT_NUMBER = ''&1'' AND BRANCH_CODE = '''||:BRN||''';' FROM DUAL;
SELECT 'DELETE CLTS_LIQ_PENAL_RATES WHERE ACCOUNT_NUMBER = ''&1'' AND BRANCH_CODE = '''||:BRN||''';' FROM DUAL;
SELECT 'DELETE CLTS_LIQ_SETTLEMENTS WHERE ACCOUNT_NUMBER = ''&1'' AND BRANCH_CODE = '''||:BRN||''';' FROM DUAL;
SELECT 'DELETE CLTB_FOGAPE_LINE_DET_ACC WHERE ACCOUNT_NUMBER = ''&1'' AND BRANCH_CODE = '''||:BRN||''';' FROM DUAL;
SELECT 'DELETE CLTB_FOGAPE_PAYMENT WHERE ACCOUNT_NUMBER = ''&1'' AND BRANCH_CODE = '''||:BRN||''';' FROM DUAL;
SELECT 'DELETE CLTB_OVERDUE_DAYS WHERE ACCOUNT_NUMBER = ''&1'' AND BRANCH_CODE = '''||:BRN||''';' FROM DUAL;
SELECT 'DELETE CLTC_ACCOUNT_ADVICE_SUPPRESS  WHERE ACCOUNT_NUMBER = ''&1'' AND BRANCH_CODE = '''||:BRN||''';' FROM DUAL;
SELECT 'DELETE CLTC_ACCOUNT_CHANGE_LOG WHERE ACCOUNT_NUMBER = ''&1'' AND BRANCH_CODE = '''||:BRN||''';' FROM DUAL;
SELECT 'DELETE CLTC_ACCOUNT_COMPONENTS WHERE ACCOUNT_NUMBER = ''&1'' AND BRANCH_CODE = '''||:BRN||''';' FROM DUAL;
SELECT 'DELETE CLTC_ACCOUNT_COMP_BALANCES WHERE ACCOUNT_NUMBER = ''&1'' AND BRANCH_CODE = '''||:BRN||''';' FROM DUAL;
SELECT 'DELETE CLTC_ACCOUNT_COMP_SCH WHERE ACCOUNT_NUMBER = ''&1'' AND BRANCH_CODE = '''||:BRN||''';' FROM DUAL;
SELECT 'DELETE CLTC_ACCOUNT_EVENTS_ADVICES WHERE ACCOUNT_NUMBER = ''&1'' AND BRANCH_CODE = '''||:BRN||''';' FROM DUAL;
SELECT 'DELETE CLTC_ACCOUNT_EVENT_USERDEF WHERE ACCOUNT_NUMBER = ''&1'' AND BRANCH_CODE = '''||:BRN||''';' FROM DUAL;
SELECT 'DELETE CLTC_ACCOUNT_HOL_PERDS WHERE ACCOUNT_NUMBER = ''&1'' AND BRANCH_CODE = '''||:BRN||''';' FROM DUAL;
SELECT 'DELETE CLTC_ACCOUNT_LINKAGES WHERE ACCOUNT_NUMBER = ''&1'' AND BRANCH_CODE = '''||:BRN||''';' FROM DUAL;
SELECT 'DELETE CLTC_ACCOUNT_MASTER WHERE ACCOUNT_NUMBER = ''&1'' AND BRANCH_CODE = '''||:BRN||''';' FROM DUAL;
SELECT 'DELETE CLTC_ACCOUNT_PARTIES WHERE ACCOUNT_NUMBER = ''&1'' AND BRANCH_CODE = '''||:BRN||''';' FROM DUAL;
SELECT 'DELETE CLTC_ACCOUNT_PROMOTIONS WHERE ACCOUNT_NUMBER = ''&1'' AND BRANCH_CODE = '''||:BRN||''';' FROM DUAL;
SELECT 'DELETE CLTC_ACCOUNT_ROLL_COMP WHERE ACCOUNT_NUMBER = ''&1'' AND BRANCH_CODE = '''||:BRN||''';' FROM DUAL;
SELECT 'DELETE CLTC_ACCOUNT_SCHEDULES WHERE ACCOUNT_NUMBER = ''&1'' AND BRANCH_CODE = '''||:BRN||''';' FROM DUAL;
SELECT 'DELETE CLTC_ACCOUNT_UDE_EFF_DATES WHERE ACCOUNT_NUMBER = ''&1'' AND BRANCH_CODE = '''||:BRN||''';' FROM DUAL;
SELECT 'DELETE CLTC_ACCOUNT_UDE_VALUES WHERE ACCOUNT_NUMBER = ''&1'' AND BRANCH_CODE = '''||:BRN||''';' FROM DUAL;
SELECT 'DELETE CLTC_AMOUNT_PAID WHERE ACCOUNT_NUMBER = ''&1'' AND BRANCH_CODE = '''||:BRN||''';' FROM DUAL;
SELECT 'DELETE CLTC_AMOUNT_RECD WHERE ACCOUNT_NUMBER = ''&1'' AND BRANCH_CODE = '''||:BRN||''';' FROM DUAL;
SELECT 'DELETE CLTC_BCH_TAX WHERE ACCOUNT_NUMBER = ''&1'' AND BRANCH_CODE = '''||:BRN||''';' FROM DUAL;
SELECT 'DELETE CLTC_BCH_TAX_HISTORY WHERE ACCOUNT_NUMBER = ''&1'' AND BRANCH_CODE = '''||:BRN||''';' FROM DUAL;
SELECT 'DELETE CLTC_DISBR_SCHEDULES WHERE ACCOUNT_NUMBER = ''&1'' AND BRANCH_CODE = '''||:BRN||''';' FROM DUAL;
SELECT 'DELETE CLTC_EVENT_CHECK_LIST WHERE ACCOUNT_NUMBER = ''&1'' AND BRANCH_CODE = '''||:BRN||''';' FROM DUAL;
SELECT 'DELETE CLTC_EVENT_OVD WHERE ACCOUNT_NUMBER = ''&1'' AND BRANCH_CODE = '''||:BRN||''';' FROM DUAL;
SELECT 'DELETE CLTC_EVENT_REMARKS WHERE ACCOUNT_NUMBER = ''&1'' AND BRANCH_CODE = '''||:BRN||''';' FROM DUAL;
SELECT 'DELETE CLTC_LIQ WHERE ACCOUNT_NUMBER = ''&1'' AND BRANCH_CODE = '''||:BRN||''';' FROM DUAL;
SELECT 'DELETE CLTC_LIQ_COMP_SETTLED WHERE ACCOUNT_NUMBER = ''&1'' AND BRANCH_CODE = '''||:BRN||''';' FROM DUAL;
SELECT 'DELETE CLTC_LIQ_COMP_SUMMARY WHERE ACCOUNT_NUMBER = ''&1'' AND BRANCH_CODE = '''||:BRN||''';' FROM DUAL;
SELECT 'DELETE CLTC_LIQ_PENAL_RATES WHERE ACCOUNT_NUMBER = ''&1'' AND BRANCH_CODE = '''||:BRN||''';' FROM DUAL;
SELECT 'DELETE CLTC_LIQ_SETTLEMENTS WHERE ACCOUNT_NUMBER = ''&1'' AND BRANCH_CODE = '''||:BRN||''';' FROM DUAL;
SELECT 'DELETE CLTB_ACCOUNT_MASTER_CUSTOM WHERE ACCOUNT_NUMBER = ''&1'' AND BRANCH_CODE = '''||:BRN||''';' FROM DUAL;
SELECT 'DELETE CLTB_WEIGHTED_AVG_TENOR WHERE ACCOUNT_NUMBER = ''&1'' AND BRANCH_CODE = '''||:BRN||''';' FROM DUAL;
SELECT 'DELETE CLTB_COMP_BAL_BREAKUP_HISTORY WHERE ACCOUNT_NUMBER = ''&1'' AND BRANCH_CODE = '''||:BRN||''';' FROM DUAL;
SELECT 'DELETE CLTB_COMP_CALC_HISTORY WHERE ACCOUNT_NUMBER = ''&1'' AND BRANCH_CODE = '''||:BRN||''';' FROM DUAL;
SELECT 'DELETE CLTB_ACC_STAT_CNG_CUSTOM WHERE ACCOUNT_NUMBER = ''&1'' AND BRANCH_CODE = '''||:BRN||''';' FROM DUAL;
SELECT 'DELETE CLTC_REVN_SCHEDULES WHERE ACCOUNT_NUMBER = ''&1'' AND BRANCH_CODE = '''||:BRN||''';' FROM DUAL;
SELECT 'DELETE FROM LMTM_COLLAT WHERE COLLATERAL_CODE IN (SELECT LINKED_REF_NO FROM CLTB_ACCOUNT_LINKAGES WHERE ACCOUNT_NUMBER = ''&1'' AND BRANCH_CODE = '''||:BRN||''');' FROM DUAL;
SELECT 'ALTER TABLE LMTB_LINE_UTILS DISABLE ALL TRIGGERS;' FROM DUAL;
SELECT 'DELETE FROM LMTB_LINE_UTILS WHERE REF_NO = ''&1'';' FROM DUAL;
SELECT 'ALTER TABLE LMTB_LINE_UTILS ENABLE ALL TRIGGERS;' FROM DUAL;
SELECT 'DELETE FROM CLTB_MIG_ACCOUNT_SCHEDULE WHERE EXT_REF_NO = '''||:ALT_ACC_NO||''';' FROM DUAL;
SELECT 'DELETE CLTC_LIQ_PREPAID WHERE ACCOUNT_NUMBER = ''&1'' AND BRANCH_CODE = '''||:BRN||''';' FROM DUAL;
SELECT 'DELETE CLTB_LIQ_PREPAID WHERE ACCOUNT_NUMBER = ''&1'' AND BRANCH_CODE = '''||:BRN||''';' FROM DUAL;
SELECT 'DELETE CLTB_MIG_ACC_SCH_PAID WHERE EXT_REF_NO = ''&1'' AND BRANCH_CODE = '''||:BRN||''';' FROM DUAL;
SELECT 'DELETE FROM CLTB_CREDIT_SCORE_HISTORY WHERE branch_code = '''||:BRN||''' and account_number = ''&1'';' FROM DUAL;

set feedback off
set sqlformat insert
select * FROM CLTB_ACCOUNT_ADVICE_SUPPRESS WHERE ACCOUNT_NUMBER = '&1' AND BRANCH_CODE = :BRN;
SELECT * FROM CLTB_ACCOUNT_APPS_MASTER WHERE ACCOUNT_NUMBER = '&1' AND BRANCH_CODE = :BRN and process_no = :process_no;
SELECT * FROM CLTP_ACCOUNT_MASTER  WHERE ACCOUNT_NUMBER = '&1' AND BRANCH_CODE = :BRN and process_no = :process_no;
SELECT * FROM CLTB_ACCOUNT_CHANGE_LOG WHERE ACCOUNT_NUMBER = '&1' AND BRANCH_CODE = :BRN;
SELECT * FROM CLTB_ACCOUNT_COMPONENTS WHERE ACCOUNT_NUMBER = '&1' AND BRANCH_CODE = :BRN;
SELECT * FROM CLTB_ACCOUNT_COMPONENTS_AMND WHERE ACCOUNT_NUMBER = '&1' AND BRANCH_CODE = :BRN;
SELECT * FROM CLTB_ACCOUNT_COMP_BALANCES WHERE ACCOUNT_NUMBER = '&1' AND BRANCH_CODE = :BRN;
SELECT * FROM CLTB_ACCOUNT_COMP_BAL_BREAKUP WHERE ACCOUNT_NUMBER = '&1' AND BRANCH_CODE = :BRN;
SELECT * FROM CLTB_ACCOUNT_COMP_BAL_CRAC WHERE ACCOUNT_NUMBER = '&1' AND BRANCH_CODE = :BRN;
SELECT * FROM CLTB_ACCOUNT_COMP_BAL_SUMMARY WHERE ACCOUNT_NUMBER = '&1' AND BRANCH_CODE = :BRN;
SELECT * FROM CLTB_ACCOUNT_COMP_CALC WHERE ACCOUNT_NUMBER = '&1' AND BRANCH_CODE = :BRN ;
SELECT * FROM CLTB_ACCOUNT_COMP_HISTORY WHERE ACCOUNT_NUMBER = '&1' AND BRANCH_CODE = :BRN;
SELECT * FROM CLTB_ACCOUNT_COMP_SCH WHERE ACCOUNT_NUMBER = '&1' AND BRANCH_CODE = :BRN ;
SELECT * FROM CLTB_ACCOUNT_COMP_SCH_AMND WHERE ACCOUNT_NUMBER = '&1' AND BRANCH_CODE = :BRN;
SELECT * FROM CLTB_ACCOUNT_COMP_SCH_CRAC WHERE ACCOUNT_NUMBER = '&1' AND BRANCH_CODE = :BRN ;
SELECT * FROM CLTB_ACCOUNT_COMP_SCH_HISTORY WHERE ACCOUNT_NUMBER = '&1' AND BRANCH_CODE = :BRN;
SELECT * FROM CLTB_ACCOUNT_DSBR_CHARGES WHERE ACCOUNT_NUMBER = '&1' AND BRANCH_CODE = :BRN;
SELECT * FROM CLTB_ACCOUNT_DSBR_DETAIL WHERE ACCOUNT_NUMBER = '&1' AND BRANCH_CODE = :BRN;
SELECT * FROM CLTB_ACCOUNT_DSBR_DETAIL_HIST WHERE ACCOUNT_NUMBER = '&1' AND BRANCH_CODE = :BRN;
SELECT * FROM CLTB_ACCOUNT_DSBR_MASTER WHERE ACCOUNT_NUMBER = '&1' AND BRANCH_CODE = :BRN;
SELECT * FROM CLTB_ACCOUNT_DSBR_MASTER_HIST WHERE ACCOUNT_NUMBER = '&1' AND BRANCH_CODE = :BRN;
SELECT * FROM CLTB_ACCOUNT_EVENTS_ADVICES WHERE ACCOUNT_NUMBER = '&1' AND BRANCH_CODE = :BRN;
SELECT * FROM CLTB_ACCOUNT_EVENTS_DIARY WHERE ACCOUNT_NUMBER = '&1' AND BRANCH_CODE = :BRN and process_no = :process_no;
SELECT * FROM CLTB_ACCOUNT_EVENTS_PROCESSED WHERE ACCOUNT_NUMBER = '&1' AND BRANCH_CODE = :BRN and process_no = :process_no;
SELECT * FROM CLTB_ACCOUNT_EVENT_USERDEF WHERE ACCOUNT_NUMBER  ='&1';
SELECT * FROM CLTB_ACCOUNT_HISTORY WHERE ACCOUNT_NUMBER = '&1' AND BRANCH_CODE = :BRN;
SELECT * FROM CLTB_ACCOUNT_HOL_PERDS WHERE ACCOUNT_NUMBER = '&1' AND BRANCH_CODE = :BRN;
SELECT * FROM CLTB_ACCOUNT_HOL_PERDS_AMND WHERE ACCOUNT_NUMBER = '&1' AND BRANCH_CODE = :BRN;
set feedback off
set sqlformat DEFAULT
SELECT 'ALTER TABLE CLTB_ACCOUNT_LINKAGES DISABLE ALL TRIGGERS;' FROM DUAL;
set feedback off
set sqlformat insert
SELECT * FROM CLTB_ACCOUNT_LINKAGES WHERE ACCOUNT_NUMBER = '&1' AND BRANCH_CODE = :BRN;
set feedback off
set sqlformat DEFAULT
SELECT 'ALTER TABLE CLTB_ACCOUNT_LINKAGES ENABLE ALL TRIGGERS;' FROM DUAL;
set feedback off
set sqlformat insert
SELECT * FROM CLTB_ACCOUNT_LINKAGES_AMND WHERE ACCOUNT_NUMBER = '&1' AND BRANCH_CODE = :BRN;
SELECT * FROM CLTB_ACCOUNT_LINKAGES_HISTORY WHERE ACCOUNT_NUMBER = '&1' AND BRANCH_CODE = :BRN;
SELECT * FROM CLTB_ACCOUNT_MASTER_AMND WHERE ACCOUNT_NUMBER = '&1' AND BRANCH_CODE = :BRN;
SELECT * FROM CLTB_ACCOUNT_MASTER_AMND_HIST WHERE ACCOUNT_NUMBER = '&1' AND BRANCH_CODE = :BRN;
SELECT * FROM CLTB_ACCOUNT_PARTIES WHERE ACCOUNT_NUMBER = '&1' AND BRANCH_CODE = :BRN;
SELECT * FROM CLTB_ACCOUNT_PARTIES_AMND WHERE ACCOUNT_NUMBER = '&1' AND BRANCH_CODE = :BRN;
SELECT * FROM CLTB_ACCOUNT_PARTIES_HISTORY WHERE ACCOUNT_NUMBER = '&1' AND BRANCH_CODE = :BRN;
SELECT * FROM CLTB_ACCOUNT_PROMOTIONS WHERE ACCOUNT_NUMBER = '&1' AND BRANCH_CODE = :BRN;
SELECT * FROM CLTB_ACCOUNT_PROMOTIONS_HIST WHERE ACCOUNT_NUMBER = '&1' AND BRANCH_CODE = :BRN;
SELECT * FROM CLTB_ACCOUNT_ROLL WHERE ACCOUNT_NUMBER = '&1' AND BRANCH_CODE = :BRN;
SELECT * FROM CLTB_ACCOUNT_ROLL_COMP WHERE ACCOUNT_NUMBER = '&1' AND BRANCH_CODE = :BRN;
SELECT * FROM CLTB_ACCOUNT_ROLL_COMP_AMND WHERE ACCOUNT_NUMBER = '&1' AND BRANCH_CODE = :BRN;
SELECT * FROM CLTB_ACCOUNT_SCHEDULES WHERE ACCOUNT_NUMBER = '&1' AND BRANCH_CODE = :BRN and process_no = :process_no;
SELECT * FROM CLTB_ACCOUNT_SCHEDULES_AMND WHERE ACCOUNT_NUMBER = '&1' AND BRANCH_CODE = :BRN;
SELECT * FROM CLTB_ACCOUNT_SCHEDULES_BAL WHERE ACCOUNT_NUMBER = '&1' AND BRANCH_CODE = :BRN;
SELECT * FROM CLTB_ACCOUNT_SCHEDULES_CRAC WHERE ACCOUNT_NUMBER = '&1' AND BRANCH_CODE = :BRN;
SELECT * FROM CLTB_ACCOUNT_SCHEDULES_HISTORY WHERE ACCOUNT_NUMBER = '&1' AND BRANCH_CODE = :BRN and process_no = :process_no;
SELECT * FROM CLTB_ACCOUNT_SCH_BAL_CRAC WHERE ACCOUNT_NUMBER = '&1' AND BRANCH_CODE = :BRN;
SELECT * FROM CLTB_ACCOUNT_STCH_CHARGES WHERE ACCOUNT_NUMBER = '&1' AND BRANCH_CODE = :BRN;
SELECT * FROM CLTB_ACCOUNT_STSH_CHARGES WHERE ACCOUNT_NUMBER = '&1' AND BRANCH_CODE = :BRN;
SELECT * FROM CLTB_ACCOUNT_UDE_EFF_DATES WHERE ACCOUNT_NUMBER = '&1' AND BRANCH_CODE = :BRN;
SELECT * FROM CLTB_ACCOUNT_UDE_VALUES WHERE ACCOUNT_NUMBER = '&1' AND BRANCH_CODE = :BRN;
SELECT * FROM CLTB_ACCOUNT_UDE_VALUES_AMND WHERE ACCOUNT_NUMBER = '&1' AND BRANCH_CODE = :BRN;
SELECT * FROM CLTB_ACCOUNT_VAMD WHERE ACCOUNT_NUMBER = '&1' AND BRANCH_CODE = :BRN;
SELECT * FROM CLTB_ACCOUNT_VAMD_HIST WHERE ACCOUNT_NUMBER = '&1' AND BRANCH_CODE = :BRN;
SELECT * FROM CLTB_ACC_COMPONENTS_AMND_HIST WHERE ACCOUNT_NUMBER = '&1' AND BRANCH_CODE = :BRN;
SELECT * FROM CLTB_ACC_COMP_BALANCES_TEMP WHERE ACCOUNT_NUMBER  = '&1' AND BRANCH_CODE = :BRN;
SELECT * FROM CLTB_ACC_COMP_SCH_AMND_HIST WHERE ACCOUNT_NUMBER = '&1' AND BRANCH_CODE = :BRN;
SELECT * FROM CLTB_ACC_DSBR_CHARGES_HIST WHERE ACCOUNT_NUMBER  = '&1' AND BRANCH_CODE = :BRN;
SELECT * FROM CLTB_ACC_HOL_PERDS_AMND_HIST WHERE ACCOUNT_NUMBER = '&1' AND BRANCH_CODE = :BRN;
SELECT * FROM CLTB_ACC_HOL_PERDS_HISTORY WHERE ACCOUNT_NUMBER = '&1' AND BRANCH_CODE = :BRN;
SELECT * FROM CLTB_ACC_LINKAGES_AMND_HIST WHERE ACCOUNT_NUMBER = '&1' AND BRANCH_CODE = :BRN;
SELECT * FROM CLTB_ACC_PARTIES_AMND_HIST WHERE ACCOUNT_NUMBER = '&1' AND BRANCH_CODE = :BRN;
SELECT * FROM CLTB_ACC_PROMOTIONS_AMND WHERE ACCOUNT_NUMBER = '&1' AND BRANCH_CODE = :BRN;
SELECT * FROM CLTB_ACC_PROMOTIONS_AMND_HIST WHERE ACCOUNT_NUMBER = '&1' AND BRANCH_CODE = :BRN;
SELECT * FROM CLTB_ACC_ROLL_COMP_AMND_HIST WHERE ACCOUNT_NUMBER = '&1' AND BRANCH_CODE = :BRN;
SELECT * FROM CLTB_ACC_SCHEDULES_AMND_HIST WHERE ACCOUNT_NUMBER = '&1' AND BRANCH_CODE = :BRN;
SELECT * FROM CLTB_ACC_UDE_EFFDT_AMND_HIST WHERE ACCOUNT_NUMBER = '&1' AND BRANCH_CODE = :BRN;
SELECT * FROM CLTB_ACC_UDE_EFF_DATES_AMND WHERE ACCOUNT_NUMBER = '&1' AND BRANCH_CODE = :BRN;
SELECT * FROM CLTB_ACC_UDE_EFF_DATES_HISTORY WHERE ACCOUNT_NUMBER = '&1' AND BRANCH_CODE = :BRN;
SELECT * FROM CLTB_ACC_UDE_VALUES_AMND_HIST WHERE ACCOUNT_NUMBER = '&1' AND BRANCH_CODE = :BRN;
SELECT * FROM CLTB_ACC_UDE_VALUES_HISTORY WHERE ACCOUNT_NUMBER = '&1' AND BRANCH_CODE = :BRN;
SELECT * FROM CLTB_ADHOC_CHARGES WHERE ACCOUNT_NUMBER = '&1' AND BRANCH_CODE = :BRN;
SELECT * FROM CLTB_AMOUNT_PAID WHERE ACCOUNT_NUMBER = '&1' AND BRANCH_CODE = :BRN;
SELECT * FROM CLTB_AMOUNT_PAID_HISTORY WHERE ACCOUNT_NUMBER = '&1' AND BRANCH_CODE = :BRN;
SELECT * FROM CLTB_AMOUNT_RECD WHERE ACCOUNT_NUMBER = '&1' AND BRANCH_CODE = :BRN;
SELECT * FROM CLTB_AMOUNT_RECD_HISTORY WHERE ACCOUNT_NUMBER = '&1' AND BRANCH_CODE = :BRN;
SELECT * FROM CLTB_BCH_TAX_HISTORY WHERE ACCOUNT_NUMBER = '&1' AND BRANCH_CODE = :BRN;
SELECT * FROM CLTB_BCH_TAX_REVERSED WHERE ACCOUNT_NUMBER = '&1' AND BRANCH_CODE = :BRN;
SELECT * FROM CLTB_CALC_DATES WHERE ACCOUNT_NUMBER = '&1' AND BRANCH_CODE = :BRN;
SELECT * FROM CLTB_COMP_BALANCES_HISTORY WHERE ACCOUNT_NUMBER = '&1' AND BRANCH_CODE = :BRN;
SELECT * FROM CLTB_DISBR_SCHEDULES WHERE ACCOUNT_NUMBER = '&1' AND BRANCH_CODE = :BRN;
SELECT * FROM CLTB_DISBR_SCHEDULES_AMND WHERE ACCOUNT_NUMBER = '&1' AND BRANCH_CODE = :BRN;
SELECT * FROM CLTB_DISBR_SCH_AMND_HIST WHERE ACCOUNT_NUMBER = '&1' AND BRANCH_CODE = :BRN;
SELECT * FROM CLTB_EVENT_ENTRIES WHERE ACCOUNT_NUMBER = '&1' AND BRANCH_CODE = :BRN;
SELECT * FROM CLTB_EVENT_ENTRIES_PENDING WHERE ACCOUNT_NUMBER = '&1' AND BRANCH_CODE = :BRN and process_no = :process_no;
SELECT * FROM CLTB_EVENT_OVD WHERE ACCOUNT_NUMBER = '&1' AND BRANCH_CODE = :BRN;
SELECT * FROM CLTB_EVENT_REMARKS WHERE ACCOUNT_NUMBER = '&1' AND BRANCH_CODE = :BRN;
SELECT * FROM CLTB_IFACEQRY_ONLINE_CALC WHERE ACCOUNT_NUMBER = '&1' AND BRANCH_CODE = :BRN;
SELECT * FROM CLTB_INACTIVE_EVENTS_DIARY WHERE ACCOUNT_NUMBER = '&1' AND BRANCH_CODE = :BRN;
SELECT * FROM CLTB_LIQ WHERE ACCOUNT_NUMBER = '&1' AND BRANCH_CODE = :BRN;
SELECT * FROM CLTB_LIQ_COMP_SETTLED WHERE ACCOUNT_NUMBER = '&1' AND BRANCH_CODE = :BRN;
SELECT * FROM CLTB_LIQ_COMP_SUMMARY WHERE ACCOUNT_NUMBER = '&1' AND BRANCH_CODE = :BRN;
SELECT * FROM CLTB_LIQ_PENAL_RATES WHERE ACCOUNT_NUMBER = '&1' AND BRANCH_CODE = :BRN;
SELECT * FROM CLTB_LIQ_SETTLEMENTS WHERE ACCOUNT_NUMBER = '&1' AND BRANCH_CODE = :BRN;
SELECT * FROM CLTB_LIQ_SUSPENSION WHERE ACCOUNT_NUMBER = '&1' AND BRANCH_CODE = :BRN;
SELECT * FROM CLTB_MANUAL_STCH WHERE ACCOUNT_NUMBER = '&1' AND BRANCH_CODE = :BRN;
SELECT * FROM CLTB_MANUAL_STSH WHERE ACCOUNT_NUMBER = '&1' AND BRANCH_CODE = :BRN;
SELECT * FROM CLTB_MIG_REFERNCE WHERE ACCOUNT_NUMBER = '&1' AND BRANCH_CODE = :BRN;
SELECT * FROM CLTB_PROCESSED_REVISIONS WHERE ACCOUNT_NUMBER = '&1' AND BRANCH_CODE = :BRN;
SELECT * FROM CLTB_PROV_HANDOFF WHERE ACCOUNT_NUMBER = '&1' AND BRANCH_CODE = :BRN;
SELECT * FROM CLTB_RECON WHERE ACCOUNT_NUMBER = '&1' AND BRANCH_CODE = :BRN;
SELECT * FROM CLTB_REVISION_ACCOUNTS WHERE ACCOUNT_NUMBER = '&1' AND BRANCH_CODE = :BRN;
SELECT * FROM CLTB_REVN_SCHEDULES WHERE ACCOUNT_NUMBER = '&1' AND BRANCH_CODE = :BRN;
SELECT * FROM CLTB_REVN_SCHEDULES_AMND WHERE ACCOUNT_NUMBER = '&1' AND BRANCH_CODE = :BRN;
SELECT * FROM CLTB_REVN_SCH_AMND_HIST WHERE ACCOUNT_NUMBER = '&1' AND BRANCH_CODE = :BRN;
SELECT * FROM CLTB_ROLL_COMPONENTS WHERE ACCOUNT_NUMBER = '&1' AND BRANCH_CODE = :BRN;
SELECT * FROM CLTB_ROLL_COMP_SETTLED WHERE ACCOUNT_NUMBER = '&1' AND BRANCH_CODE = :BRN;
SELECT * FROM CLTB_ROLL_SETTLEMENTS WHERE ACCOUNT_NUMBER = '&1' AND BRANCH_CODE = :BRN;
SELECT * FROM CLTB_SDE_VALUES WHERE ACCOUNT_NUMBER = '&1' AND BRANCH_CODE = :BRN;
SELECT * FROM CLTP_ACCOUNT_COMP_BALANCES WHERE ACCOUNT_NUMBER = '&1' AND BRANCH_CODE = :BRN ;
SELECT * FROM CLTP_ACCOUNT_COMP_SCH WHERE ACCOUNT_NUMBER = '&1' AND BRANCH_CODE = :BRN;
SELECT * FROM CLTP_ACCOUNT_SCHEDULES WHERE ACCOUNT_NUMBER = '&1' AND BRANCH_CODE = :BRN and process_no = :process_no;
SELECT * FROM CLTP_LIQ WHERE ACCOUNT_NUMBER = '&1' AND BRANCH_CODE = :BRN;
SELECT * FROM CLTS_LIQ WHERE ACCOUNT_NUMBER = '&1' AND BRANCH_CODE = :BRN;
SELECT * FROM CLTS_LIQ_COMP_SETTLED WHERE ACCOUNT_NUMBER = '&1' AND BRANCH_CODE = :BRN;
SELECT * FROM CLTS_LIQ_COMP_SUMMARY WHERE ACCOUNT_NUMBER = '&1' AND BRANCH_CODE = :BRN;
SELECT * FROM CLTS_LIQ_PENAL_RATES WHERE ACCOUNT_NUMBER = '&1' AND BRANCH_CODE = :BRN;
SELECT * FROM CLTS_LIQ_SETTLEMENTS WHERE ACCOUNT_NUMBER = '&1' AND BRANCH_CODE = :BRN;
SELECT * FROM CLTC_ACCOUNT_ADVICE_SUPPRESS WHERE ACCOUNT_NUMBER = '&1' AND BRANCH_CODE = :BRN;
SELECT * FROM CLTB_ACC_STAT_CNG_CUSTOM WHERE ACCOUNT_NUMBER = '&1' AND BRANCH_CODE = :BRN;
SELECT * FROM CLTC_ACCOUNT_CHANGE_LOG WHERE ACCOUNT_NUMBER = '&1' AND BRANCH_CODE = :BRN;
SELECT * FROM CLTP_ACCOUNT_COMP_CALC WHERE ACCOUNT_NUMBER = '&1' AND BRANCH_CODE = :BRN;
SELECT * FROM CLTP_ACCOUNT_COMP_BAL_BREAKUP WHERE ACCOUNT_NUMBER = '&1' AND BRANCH_CODE = :BRN;
SELECT * FROM CLTC_ACCOUNT_COMPONENTS WHERE ACCOUNT_NUMBER = '&1' AND BRANCH_CODE = :BRN;
SELECT * FROM CLTC_ACCOUNT_COMP_BALANCES WHERE ACCOUNT_NUMBER = '&1' AND BRANCH_CODE = :BRN;
SELECT * FROM CLTC_ACCOUNT_COMP_SCH WHERE ACCOUNT_NUMBER = '&1' AND BRANCH_CODE = :BRN;
SELECT * FROM CLTC_ACCOUNT_EVENTS_ADVICES WHERE ACCOUNT_NUMBER = '&1' AND BRANCH_CODE = :BRN;
SELECT * FROM CLTC_ACCOUNT_EVENT_USERDEF WHERE ACCOUNT_NUMBER = '&1' AND BRANCH_CODE = :BRN;
SELECT * FROM CLTC_ACCOUNT_HOL_PERDS WHERE ACCOUNT_NUMBER = '&1' AND BRANCH_CODE = :BRN;
SELECT * FROM CLTC_ACCOUNT_LINKAGES WHERE ACCOUNT_NUMBER = '&1' AND BRANCH_CODE = :BRN;
SELECT * FROM CLTC_ACCOUNT_MASTER WHERE ACCOUNT_NUMBER = '&1' AND BRANCH_CODE = :BRN;
SELECT * FROM CLTC_ACCOUNT_PARTIES WHERE ACCOUNT_NUMBER = '&1' AND BRANCH_CODE = :BRN;
SELECT * FROM CLTC_ACCOUNT_PROMOTIONS WHERE ACCOUNT_NUMBER = '&1' AND BRANCH_CODE = :BRN;
SELECT * FROM CLTC_ACCOUNT_ROLL_COMP WHERE ACCOUNT_NUMBER = '&1' AND BRANCH_CODE = :BRN;
SELECT * FROM CLTC_ACCOUNT_SCHEDULES WHERE ACCOUNT_NUMBER = '&1' AND BRANCH_CODE = :BRN;
SELECT * FROM CLTC_ACCOUNT_UDE_EFF_DATES WHERE ACCOUNT_NUMBER = '&1' AND BRANCH_CODE = :BRN;
SELECT * FROM CLTC_ACCOUNT_UDE_VALUES WHERE ACCOUNT_NUMBER = '&1' AND BRANCH_CODE = :BRN;
SELECT * FROM CLTC_AMOUNT_PAID WHERE ACCOUNT_NUMBER = '&1' AND BRANCH_CODE = :BRN;
SELECT * FROM CLTC_AMOUNT_RECD WHERE ACCOUNT_NUMBER = '&1' AND BRANCH_CODE = :BRN;
SELECT * FROM CLTC_BCH_TAX WHERE ACCOUNT_NUMBER = '&1' AND BRANCH_CODE = :BRN;
SELECT * FROM CLTC_BCH_TAX_HISTORY WHERE ACCOUNT_NUMBER = '&1' AND BRANCH_CODE = :BRN;
SELECT * FROM CLTC_DISBR_SCHEDULES WHERE ACCOUNT_NUMBER = '&1' AND BRANCH_CODE = :BRN;
SELECT * FROM CLTC_EVENT_CHECK_LIST WHERE ACCOUNT_NUMBER = '&1' AND BRANCH_CODE = :BRN;
SELECT * FROM CLTC_EVENT_OVD WHERE ACCOUNT_NUMBER = '&1' AND BRANCH_CODE = :BRN;
SELECT * FROM CLTC_EVENT_REMARKS WHERE ACCOUNT_NUMBER = '&1' AND BRANCH_CODE = :BRN;
SELECT * FROM CLTC_LIQ WHERE ACCOUNT_NUMBER = '&1' AND BRANCH_CODE = :BRN;
SELECT * FROM CLTC_LIQ_COMP_SETTLED WHERE ACCOUNT_NUMBER = '&1' AND BRANCH_CODE = :BRN;
SELECT * FROM CLTC_LIQ_COMP_SUMMARY WHERE ACCOUNT_NUMBER = '&1' AND BRANCH_CODE = :BRN;
SELECT * FROM CLTB_COMP_CALC_HISTORY WHERE ACCOUNT_NUMBER = '&1' AND BRANCH_CODE = :BRN;
SELECT * FROM CLTB_COMP_BAL_BREAKUP_HISTORY WHERE ACCOUNT_NUMBER = '&1' AND BRANCH_CODE = :BRN;
SELECT * FROM CLTC_LIQ_PENAL_RATES WHERE ACCOUNT_NUMBER = '&1' AND BRANCH_CODE = :BRN;
SELECT * FROM CLTC_LIQ_SETTLEMENTS WHERE ACCOUNT_NUMBER = '&1' AND BRANCH_CODE = :BRN;
SELECT * FROM CLTB_FOGAPE_LINE_DET_ACC WHERE ACCOUNT_NUMBER = '&1' AND BRANCH_CODE = :BRN;
SELECT * FROM CLTB_FOGAPE_PAYMENT WHERE ACCOUNT_NUMBER = '&1' AND BRANCH_CODE = :BRN;
SELECT * FROM CLTC_REVN_SCHEDULES WHERE ACCOUNT_NUMBER = '&1' AND BRANCH_CODE = :BRN;
SELECT * FROM CLTB_OVERDUE_DAYS WHERE ACCOUNT_NUMBER = '&1' AND BRANCH_CODE = :BRN;
SELECT * FROM LMTM_COLLAT WHERE COLLATERAL_CODE IN (SELECT LINKED_REF_NO FROM CLTB_ACCOUNT_LINKAGES WHERE ACCOUNT_NUMBER = '&1' AND BRANCH_CODE = :BRN);
set feedback off
set sqlformat default
SELECT 'ALTER TABLE LMTB_LINE_UTILS DISABLE ALL TRIGGERS;' FROM DUAL;
set feedback off
set sqlformat insert
SELECT * FROM LMTB_LINE_UTILS WHERE REF_NO = '&1';
set feedback off
set sqlformat default
SELECT 'ALTER TABLE LMTB_LINE_UTILS ENABLE ALL TRIGGERS;' FROM DUAL;
set feedback off
set sqlformat insert
SELECT * FROM CLTB_ACCOUNT_PROPERTY_HIST WHERE ACCOUNT_NUMBER = '&1' AND BRANCH_CODE = :BRN;
SELECT * FROM CLTB_ACCOUNT_CREDIT_SCORE WHERE ACCOUNT_NUMBER = '&1' AND BRANCH_CODE = :BRN;
SELECT * FROM CLTB_ASSET_VEHICLE_HISTORY WHERE ACCOUNT_NUMBER = '&1' AND BRANCH_CODE = :BRN;
SELECT * FROM CLTB_ASSET_HOME_HISTORY WHERE ACCOUNT_NUMBER = '&1' AND BRANCH_CODE = :BRN;
SELECT * FROM CLTB_ASSET_OTHERS_HISTORY WHERE ACCOUNT_NUMBER = '&1' AND BRANCH_CODE = :BRN;
SELECT * FROM CLTB_LIQ_C WHERE ACCOUNT_NUMBER = '&1' AND BRANCH_CODE = :BRN;
SELECT * FROM CLTB_LIQ_SETTLEMENTS_C WHERE ACCOUNT_NUMBER = '&1' AND BRANCH_CODE = :BRN;
SELECT * FROM CLTB_ACCOUNT_MASTER_CUSTOM WHERE  ACCOUNT_NUMBER = '&1' AND BRANCH_CODE = :BRN;
SELECT * FROM CLTB_WEIGHTED_AVG_TENOR WHERE ACCOUNT_NUMBER = '&1' AND BRANCH_CODE = :BRN;
SELECT * FROM CLTB_LIQ_PREPAID WHERE ACCOUNT_NUMBER = '&1' AND BRANCH_CODE = :BRN ;
SELECT * FROM CLTC_LIQ_PREPAID WHERE ACCOUNT_NUMBER = '&1' AND BRANCH_CODE = :BRN ;
SELECT * FROM CLTB_MIG_ACC_SCH_PAID WHERE EXT_REF_NO = '&1' AND BRANCH_CODE = :BRN ;
SELECT * FROM CLTB_CREDIT_SCORE_HISTORY  WHERE ACCOUNT_NUMBER = '&1'  AND BRANCH_CODE = :BRN;
set feedback off
set sqlformat default
SELECT 'DELETE FROM STTM_CUSTOMER WHERE CUSTOMER_NO = '||:CUSTOMER_NO||';' from Dual ;
set feedback off
set sqlformat insert
select * from  STTM_CUSTOMER Where CUSTOMER_NO = :CUSTOMER_NO;
set feedback off
set sqlformat default
SELECT 'ALTER TABLE STTM_CUSTOMER_C DISABLE ALL TRIGGERS;' from dual;
SELECT 'DELETE FROM STTM_CUSTOMER_C WHERE CUSTOMER_NO = '||:CUSTOMER_NO||';' from Dual ;
set feedback off
set sqlformat insert
SELECT * FROM STTM_CUSTOMER_C Where CUSTOMER_NO = :CUSTOMER_NO;
set feedback off
set sqlformat default
SELECT 'ALTER TABLE STTM_CUSTOMER_C ENABLE ALL TRIGGERS;' from dual;
SELECT 'DELETE FROM STTM_CUST_PERSONAL WHERE CUSTOMER_NO = '||:CUSTOMER_NO||';' from Dual ;
set feedback off
set sqlformat insert
SELECT * FROM STTM_CUST_PERSONAL WHERE CUSTOMER_NO = :CUSTOMER_NO;
set feedback off
set sqlformat default
SELECT 'DELETE FROM GETM_LIAB WHERE id = '||:id||';' from Dual ;
set feedback off
set sqlformat insert
SELECT * FROM GETM_LIAB Where id = :id;
set feedback off
set sqlformat default
SELECT 'DELETE FROM GETM_LIAB_CUST WHERE LIAB_ID = '||:id||';' from Dual ;
set feedback off
set sqlformat insert
SELECT * FROM GETM_LIAB_CUST Where LIAB_ID = :id;
set feedback off
set sqlformat default
SELECT 'DELETE FROM GETM_FACILITY WHERE LIAB_ID = '||:id||';' from Dual ;
set feedback off
set sqlformat insert
SELECT * FROM GETM_FACILITY Where LIAB_ID = :id;
set feedback off
set sqlformat default
SELECT 'DELETE FROM GETB_UTILS WHERE LIAB_ID = '||:id||';' from Dual ;
set feedback off
set sqlformat insert
SELECT * FROM GETB_UTILS Where LIAB_ID = :id;
set feedback off
set sqlformat default
SELECT 'DELETE FROM GETB_UTILS_LOG WHERE UTIL_ID = '||chr(39)||:util_id||chr(39)||';' from Dual ;
set feedback off
set sqlformat insert
SELECT * FROM GETB_UTILS_LOG Where UTIL_ID = :util_id;
set feedback off
set sqlformat default
SELECT 'DELETE FROM GETH_UTILS WHERE UTIL_ID = '||chr(39)||:util_id||chr(39)||';' from Dual ;
set feedback off
set sqlformat insert
SELECT * FROM GETH_UTILS Where UTIL_ID = :util_id;
set feedback off
set sqlformat default
SELECT 'COMMIT;' FROM DUAL;
SELECT 'SPOOL OFF' FROM DUAL;
SET AUTOPRINT off
SET ECHO OFF
SPOOL OFF
SET FEEDBACK on
SET VERIFY ON
/

