### Logs
LOG_PATH=log/EODBATCH/
LOG_FILENAME=BatchReportDebug
ERROR_LOG_FILENAME = BatchReportError
MESSAGE_LOG_FILENAME=BatchReportMessage

## Upload File details
UPLOAD_FILE_PATH=upload/EODBATCH/Template/
UPLOAD_SQL_FILE_NAME=EODBatch.sql
UPLOAD_HIST_SQL_FILE_NAME=EODBatchHistory.sql

##  HTML Template
UPLOAD_HTML_FILE_NAME=BatchReport.html

##### Issue details
UPLOAD_EOD_ISSUE_DETAILS = ../upload/EODBATCH/EODBatchIssue.properties

## Output File details
OUTPUT_FILE_PATH=output/EODBATCH/
OUTPUT_FILE_NAME=BatchReport
OUTPUT_FILE_EXT=.html


STTM_LCL_HOLIDAY_TABLE_QUERY= SELECT HOLIDAY_LIST FROM sttm_lcl_holiday WHERE MONTH = '%DAY_OF_MONTH%' AND YEAR = '%YEAR%' AND branch_code = '001'
