### Logs
LOG_PATH=log/EODBatchEvent/
LOG_FILENAME=FBCLEODBatchEventDebug
ERROR_LOG_FILENAME = FBCLEODBatchEventError
MESSAGE_LOG_FILENAME=FBCLCEODBatchEventMessage


## Upload File details
UPLOAD_FILE_PATH=upload/EODBatchEvent/Template/
BOD_UPLOAD_FILE_NAME=BODBatchEvent.sql
EOD_UPLOAD_FILE_NAME=EODBatchEvent.sql

##  HTML Template
UPLOAD_HTML_FILE_NAME=EODEventReport.html

## Output File details
OUTPUT_FILE_PATH=output/EODBatchEvent/
OUTPUT_FILE_NAME=EODBatchEvent
OUTPUT_FILE_EXT=.html

ORACLE_LOGO_URL=<img src="https://www.oracle.com/a/ocom/img/oracle-logo.svg" alt="Oracle Logo" class="top-right-logo">


STTM_DATES_QUERY = SELECT TODAY,PREV_WORKING_DAY FROM  sttm_dates WHERE bRANCH_CODE = '001'

STTM_LCL_HOLIDAY_TABLE_QUERY=SELECT HOLIDAY_LIST FROM sttm_lcl_holiday WHERE MONTH = '%MONTH%' AND YEAR = '%YEAR%' AND branch_code = '001'
#########################################################################################

EOD_EVENT_LIST=DEVENGO DE CREDITOS ACTIVOS,CUENTAS CASA QUE GENERAN DEVENGO,CUENTAS CASA - CALCULO DE SALDO A LA FECHA DE VALOR,CUENTAS CASA - CALCULO DE SALDO A LA FECHA DE TRANSACCION,CANTIDAD DE RESOLUCIONES DE IC DEL DIA,TRANSFERENCIAS DE LINEA DE CREDITO,RECUPERACION DE LINEA DE CREDITO,LIBERACION DE MONTOS BLOQUEADOS,REGISTROS PARA HANDOFF FILE - HANDOFF,REGISTROS PARA HANDOFF FILE - GL,REGISTROS PARA HANDOFF FILE - ENTRIES,CREACION DE CREDITOS POR SOBREGIRO DE CUENTA VISTA,PRE-GENERACION DE CARTOLA - CUENTA CORRIENTE y CUENTA AHORRO,PRE-GENERACION DE CARTOLA - LDC,CUENTAS CASA QUE GENERAN LIQUIDACIÓN,CUENTAS CASA QUE GENERAN LIQUIDACIÓN,CUENTAS CASA QUE GENERAN LIQUIDACION

BOD_EVENT_LIST=TRANSACIONES DESTANQUEADOS - CASA,TRANSACIONES DESTANQUEADOS - CL,PENALIDAD CREDITOS,SEQUENCIAS RESETEADAS EN BOD