 SELECT 'EOD' "PROCESS",
       X.EOD_DATE,
       MIN(X.START_TIME) START_TIME,
       MAX(X.END_TIME) END_TIME,
       TO_CHAR(DATE '1-1-1' + NUMTODSINTERVAL(MAX(X.END_TIME) - MIN(X.START_TIME), 'day'), 'hh24:mi:ss') TIME_TAKEN
  FROM AETB_EOC_RUNCHART_HISTORY X
  LEFT JOIN AETM_EOC_GROUP_BRANCHES Y
    ON X.BRANCH_CODE = Y.BRANCH_CODE
 WHERE EOD_DATE = to_date('%PROCESSED_DATE%','dd-mm-yyyy')
   AND EOC_STAGE_STATUS = 'C'
   AND X.BRANCH_CODE IN (SELECT BRANCH_CODE FROM STTM_BRANCH
                          WHERE RECORD_STAT = 'O' AND PARENT_BRANCH = '001')
   AND X.EOC_STAGE IN ('POSTEOTI_1', 'POSTEOTI_3', 'POSTEOTI_2', 'POSTEOFI_2', 'POSTEOFI_1', 'POSTEOFI_3', 'MARKEOFI', 'MARKEOTI', 'MARKTIMELVL9')
 GROUP BY X.EOD_DATE
UNION ALL
SELECT 'BOD' "PROCESS",
       X.EOD_DATE,
       MIN(X.START_TIME) START_TIME,
       MAX(X.END_TIME) END_TIME,
       TO_CHAR(DATE '1-1-1' + NUMTODSINTERVAL(MAX(X.END_TIME) - MIN(X.START_TIME), 'day'), 'hh24:mi:ss') TIME_TAKEN
  FROM AETB_EOC_RUNCHART_HISTORY X
  LEFT JOIN AETM_EOC_GROUP_BRANCHES Y
    ON X.BRANCH_CODE = Y.BRANCH_CODE
 WHERE EOD_DATE = to_date('%PROCESSED_DATE%','dd-mm-yyyy')
   AND EOC_STAGE_STATUS = 'C'
   AND X.BRANCH_CODE IN (SELECT BRANCH_CODE FROM STTM_BRANCH
                          WHERE RECORD_STAT = 'O' AND PARENT_BRANCH = '001')
   AND X.EOC_STAGE IN ('MARKBOD', 'MARKEOD', 'MARKTI', 'POSTBOD_1', 'POSTBOD_2', 'POSTBOD_3', 'POSTEOD_1', 'POSTEOD_2', 'POSTEOD_3')
 GROUP BY X.EOD_DATE
--SPLIT--
SELECT 'EOD' "PROCESS",
       X.EOD_DATE,
       MIN(X.START_TIME) START_TIME,
       MAX(X.END_TIME) END_TIME,
       TO_CHAR(DATE '1-1-1' + NUMTODSINTERVAL(MAX(X.END_TIME) - MIN(X.START_TIME), 'day'), 'hh24:mi:ss') TIME_TAKEN
  FROM AETB_EOC_RUNCHART_HISTORY X
  LEFT JOIN AETM_EOC_GROUP_BRANCHES Y
    ON X.BRANCH_CODE = Y.BRANCH_CODE
 WHERE EOD_DATE = to_date('%PROCESSED_DATE%','dd-mm-yyyy')
   AND EOC_STAGE_STATUS = 'C'
   AND X.BRANCH_CODE IN (SELECT BRANCH_CODE FROM STTM_BRANCH
                          WHERE RECORD_STAT = 'O' AND PARENT_BRANCH = 'A00')
   AND X.EOC_STAGE IN ('POSTEOTI_1', 'POSTEOTI_3', 'POSTEOTI_2', 'POSTEOFI_2', 'POSTEOFI_1', 'POSTEOFI_3', 'MARKEOFI', 'MARKEOTI', 'MARKTIMELVL9')
 GROUP BY X.EOD_DATE
UNION ALL
SELECT 'BOD' "PROCESS",
       X.EOD_DATE,
       MIN(X.START_TIME) START_TIME,
       MAX(X.END_TIME) END_TIME,
       TO_CHAR(DATE '1-1-1' + NUMTODSINTERVAL(MAX(X.END_TIME) - MIN(X.START_TIME), 'day'), 'hh24:mi:ss') TIME_TAKEN
  FROM AETB_EOC_RUNCHART_HISTORY X
  LEFT JOIN AETM_EOC_GROUP_BRANCHES Y
    ON X.BRANCH_CODE = Y.BRANCH_CODE
 WHERE EOD_DATE = to_date('%PROCESSED_DATE%','dd-mm-yyyy')
   AND EOC_STAGE_STATUS = 'C'
   AND X.BRANCH_CODE IN (SELECT BRANCH_CODE FROM STTM_BRANCH
                          WHERE RECORD_STAT = 'O' AND PARENT_BRANCH = 'A00')
   AND X.EOC_STAGE IN ('MARKBOD', 'MARKEOD', 'MARKTI', 'POSTBOD_1', 'POSTBOD_2', 'POSTBOD_3', 'POSTEOD_1', 'POSTEOD_2', 'POSTEOD_3')
 GROUP BY X.EOD_DATE
 --SPLIT--
 SELECT 'EOD' "PROCESS",
       X.EOD_DATE,
       MIN(X.START_TIME) START_TIME,
       MAX(X.END_TIME) END_TIME,
       TO_CHAR(DATE '1-1-1' + NUMTODSINTERVAL(MAX(X.END_TIME) - MIN(X.START_TIME), 'day'), 'hh24:mi:ss') TIME_TAKEN
  FROM AETB_EOC_RUNCHART_HISTORY X
  LEFT JOIN AETM_EOC_GROUP_BRANCHES Y
    ON X.BRANCH_CODE = Y.BRANCH_CODE
 WHERE EOD_DATE = to_date('%PROCESSED_DATE%','dd-mm-yyyy')
   AND EOC_STAGE_STATUS = 'C'
   AND X.EOC_STAGE IN ('POSTEOTI_1', 'POSTEOTI_3', 'POSTEOTI_2', 'POSTEOFI_2', 'POSTEOFI_1', 'POSTEOFI_3', 'MARKEOFI', 'MARKEOTI', 'MARKTIMELVL9')
 GROUP BY X.EOD_DATE
UNION ALL
SELECT 'BOD' "PROCESS",
       X.EOD_DATE,
       MIN(X.START_TIME) START_TIME,
       MAX(X.END_TIME) END_TIME,
       TO_CHAR(DATE '1-1-1' + NUMTODSINTERVAL(MAX(X.END_TIME) - MIN(X.START_TIME), 'day'), 'hh24:mi:ss') TIME_TAKEN
  FROM AETB_EOC_RUNCHART_HISTORY X
  LEFT JOIN AETM_EOC_GROUP_BRANCHES Y
    ON X.BRANCH_CODE = Y.BRANCH_CODE
 WHERE EOD_DATE = to_date('%PROCESSED_DATE%','dd-mm-yyyy')
   AND EOC_STAGE_STATUS = 'C'
   AND X.EOC_STAGE IN ('MARKBOD', 'MARKEOD', 'MARKTI', 'POSTBOD_1', 'POSTBOD_2', 'POSTBOD_3', 'POSTEOD_1', 'POSTEOD_2', 'POSTEOD_3')
 GROUP BY X.EOD_DATE
 --SPLIT--
 SELECT 'EOD' "PROCESS",
           X.EOD_DATE,
           MIN(X.START_TIME) START_TIME,
           MAX(X.END_TIME) END_TIME,
           TO_CHAR(DATE '1-1-1' + NUMTODSINTERVAL(MAX(X.END_TIME) - MIN(X.START_TIME), 'day'), 'hh24:mi:ss') TIME_TAKEN
      FROM AETB_EOC_PROGRAMS_HISTORY X
      LEFT JOIN AETM_EOC_GROUP_BRANCHES Y
        ON X.BRANCH_CODE = Y.BRANCH_CODE
    WHERE EOD_DATE = to_date('%PROCESSED_DATE%','dd-mm-yyyy')
       AND X.EOC_STAGE IN ('POSTEOTI_1', 'POSTEOTI_3', 'POSTEOTI_2', 'POSTEOFI_2', 'POSTEOFI_1', 'POSTEOFI_3')
    GROUP BY X.EOD_DATE
    UNION ALL
    SELECT 'BOD' "PROCESS",
           X.EOD_DATE,
           MIN(X.START_TIME) START_TIME,
           MAX(X.END_TIME) END_TIME,
           TO_CHAR(DATE '1-1-1' + NUMTODSINTERVAL(MAX(X.END_TIME) - MIN(X.START_TIME), 'day'), 'hh24:mi:ss') TIME_TAKEN
      FROM AETB_EOC_PROGRAMS_HISTORY X
      LEFT JOIN AETM_EOC_GROUP_BRANCHES Y
        ON X.BRANCH_CODE = Y.BRANCH_CODE
    WHERE EOD_DATE = to_date('%PROCESSED_DATE%','dd-mm-yyyy')
       AND X.EOC_STAGE IN  ('MARKBOD', 'MARKEOD', 'MARKTI', 'POSTBOD_1', 'POSTBOD_2', 'POSTBOD_3', 'POSTEOD_1', 'POSTEOD_2', 'POSTEOD_3')
    GROUP BY X.EOD_DATE
