"""Automatic retention for spool files generated by Oracle Tasks Chile."""
from __future__ import annotations

from dataclasses import dataclass
from datetime import datetime, timedelta, timezone
import fnmatch
import logging
import os
from pathlib import Path
from typing import Iterable, Sequence

from paths import SPOOLS_CL_OUT_DIR, SPOOLS_CMR_OUT_DIR, SPOOLS_SAVINGS_OUT_DIR


log = logging.getLogger(__name__)

RETENTION_DAYS = 30

_CL_PATTERNS = (
    "cl_acc_spool_*.sql",
    "cl_spools_*.zip",
)
_CMR_PATTERNS = (
    "cl_acc_spool_*.sql",
    "cmr_spools_*.zip",
)
_SAVINGS_PATTERNS = (
    "ic_account_data_*.inc",
    "ic_account_data_*_apply.log",
    "savings_spools_*.zip",
)


@dataclass(frozen=True)
class CleanupResult:
    scanned: int = 0
    deleted: int = 0
    failed: int = 0

    def __add__(self, other: "CleanupResult") -> "CleanupResult":
        return CleanupResult(
            scanned=self.scanned + other.scanned,
            deleted=self.deleted + other.deleted,
            failed=self.failed + other.failed,
        )


def cleanup_managed_spools(
    *,
    now: datetime | None = None,
    rules: Sequence[tuple[Path, Sequence[str]]] | None = None,
) -> CleanupResult:
    """Delete recognized spool artifacts older than the retention period."""
    active_rules = rules
    if active_rules is None:
        active_rules = (
            (SPOOLS_CL_OUT_DIR, _CL_PATTERNS),
            (SPOOLS_CMR_OUT_DIR, _CMR_PATTERNS),
            (SPOOLS_SAVINGS_OUT_DIR, _SAVINGS_PATTERNS),
        )
    cutoff = _cutoff_timestamp(now)
    total = CleanupResult()
    for root, patterns in active_rules:
        total += _cleanup_directory(
            Path(root),
            patterns,
            cutoff=cutoff,
            recursive=True,
            source="managed spool folder",
        )
    log.info(
        "Managed spool retention finished retention_days=%s scanned=%s deleted=%s failed=%s",
        RETENTION_DAYS,
        total.scanned,
        total.deleted,
        total.failed,
    )
    return total


def cleanup_extract_archives(
    directory: str | Path,
    archive_prefixes: Sequence[str],
    *,
    now: datetime | None = None,
) -> CleanupResult:
    """Clean old app-generated ZIPs from a user-selected export folder."""
    patterns = tuple(f"{prefix.lower()}*.zip" for prefix in archive_prefixes)
    result = _cleanup_directory(
        Path(directory),
        patterns,
        cutoff=_cutoff_timestamp(now),
        recursive=False,
        source="selected extract folder",
    )
    log.info(
        "Extract archive retention finished directory=%s retention_days=%s "
        "scanned=%s deleted=%s failed=%s",
        directory,
        RETENTION_DAYS,
        result.scanned,
        result.deleted,
        result.failed,
    )
    return result


def _cutoff_timestamp(now: datetime | None) -> float:
    current = now or datetime.now(timezone.utc)
    if current.tzinfo is None:
        current = current.replace(tzinfo=timezone.utc)
    return (current - timedelta(days=RETENTION_DAYS)).timestamp()


def _cleanup_directory(
    root: Path,
    patterns: Sequence[str],
    *,
    cutoff: float,
    recursive: bool,
    source: str,
) -> CleanupResult:
    if not root.is_dir() or root.is_symlink():
        return CleanupResult()

    scanned = 0
    deleted = 0
    failed = 0
    normalized_patterns = tuple(pattern.lower() for pattern in patterns)

    try:
        candidates = _iter_files(root, recursive=recursive)
        for path in candidates:
            if not _matches(path, normalized_patterns):
                continue
            scanned += 1
            try:
                if path.stat().st_mtime >= cutoff:
                    continue
                path.unlink()
                deleted += 1
                log.info("Deleted expired spool artifact source=%s path=%s", source, path)
            except OSError:
                failed += 1
                log.exception("Could not delete expired spool artifact source=%s path=%s", source, path)
    except OSError:
        failed += 1
        log.exception("Could not scan spool retention folder source=%s path=%s", source, root)

    return CleanupResult(scanned=scanned, deleted=deleted, failed=failed)


def _iter_files(root: Path, *, recursive: bool) -> Iterable[Path]:
    if not recursive:
        with os.scandir(root) as entries:
            for entry in entries:
                if entry.is_symlink():
                    continue
                if entry.is_file(follow_symlinks=False):
                    yield Path(entry.path)
        return

    pending = [root]
    while pending:
        current = pending.pop()
        with os.scandir(current) as entries:
            for entry in entries:
                if entry.is_symlink():
                    continue
                if entry.is_dir(follow_symlinks=False):
                    pending.append(Path(entry.path))
                elif entry.is_file(follow_symlinks=False):
                    yield Path(entry.path)


def _matches(path: Path, patterns: Sequence[str]) -> bool:
    name = path.name.lower()
    return any(fnmatch.fnmatchcase(name, pattern) for pattern in patterns)
