######  DB Details  ########
FB_COUNTRY = CL

###5 seconds between retries ###
DB_CONNECTION_RETRY = 5
DB_CONNECTION_RETRY_DELAY = 5000

######  DB Details  ########
DRIVER_CLASS= oracle.jdbc.OracleDriver
CL_DEV_DB_URL=jdbc:oracle:thin:@//10.217.123.19:1541/clflqa01_scl1jz.netpvtdb01.vcnqaclstgo.oraclevcn.com
CL_DEV_DB_USER=__CREDENTIAL_FROM_APP__
CL_DEV_DB_PASSWORD=__CREDENTIAL_FROM_APP__

##### CL PROD ##########################################
CL_PROD_DB_URL=jdbc:oracle:thin:@//bfa-cl-flx-db-savap1-priv.fifcore.com:1541/bfclflxprd.val.fif.tech
CL_PROD_DB_USER=__CREDENTIAL_FROM_APP__
CL_PROD_DB_PASSWORD=__CREDENTIAL_FROM_APP__

###### ENV List  ###########
DB_ENV_LIST = DEV,QA,PROD

## Default log file path and file Name
EXT_PATH_LOG_ENABLED =Y
LOG_PATH=log/
LOG_FILENAME=FBCLDebug
ERROR_LOG_FILENAME =FBCLError
MESSAGE_LOG_FILENAME=FBCLMessage

### Should be present ###
LOG_ENABLED=Y

###### External Custom Property Details ########
EXT_CUSTOMERDATA_PROPS= BUPCL/clbupscript.properties
EXT_CHISALCA_PROPS= Chisalca/FBCLChisalca.properties
EXT_VOL_PROPS= Volumetric/FBCLVolumetric.properties
EXT_EOD_EVENT_BATCH= EODBatchEvent/EODBatchEvent.properties
